
<?php
/**
 * @var $form \BancaExaminadora\Form\BancaExaminadora */

/** @var $lista \BancaExaminadora\Service\BancaExaminadora
 */

?>

<div class="page-head">
    <h2>Listar data das Bancas</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="col-md-12">
            <a class="btn btn-default" href="<?=$this->url('navegacao',array('controller'=>$controller,'action'=>'cadastro'))?>" title="Adicionar nova Banca">Nova Banca Examinadora</a>
        </div>
    </div>
    <br />
    <div class="row" id="banca-examinadora"></div>
</div>

<script>
    $(function () {

        $.ajax({
            type: "post",
            dataType: "text",
            cache: false,
            url: '/banca_examinadora-bancaexaminadora/index-pagination',
            async: true,
            data: {
            },
            beforeSend: function () {

                $('#banca-examinadora').html(
                    '<div class="row"><div class="col-md-12 text-center"><p><img src="/assets/img/carregando.gif"><p></div></div>'
                );
            },
            success: function (data) {

                $('#banca-examinadora').html(data);
            }
        });

    })
</script>
