<?php
?>
<div class="page-head">
    <h2>Dados da Banca</h2>
</div>
<div class="cl-mcont">
    <div class="row"
    <div class="block-flat">
        <div class="content">
            <fieldset>
                <?php if (isset($dados_banca) && $dados_banca) { ?>
                    <div class="bs-callout bs-callout-primary">
                        <ul class="primary">
                            <li><b>Data da
                                    Banca:</b> <?= Estrutura\Helpers\Data::converterDataBancoMySQL2Brazil($dados_banca['dt_banca']) ?>
                            </li>
                            <li><b>Quant. Professores:</b>
                                <text id="count"><?= count($lista_inscritos) ?></text>
                            </li>
                        </ul>
                    </div>
                <?php } ?>
            </fieldset>
            <div id="msg"></div>
            <form action="#" method="post" id="form_realizar_inscricao">
                <input type="hidden" class="form-control" id="id_banca_examinadora" name="id_banca_examinadora"
                       value="<?= $dados_banca['id_banca_examinadora'] ?>">
                <div class="row">
                    <div class="form-group">
                        <div class="col-md-4">
                            <label for="nm_professor">Nome do Professor</label>
                            <input type="text" value="" data-error="Campo é obrigatório." required="required"
                                   class="form-control" id="nm_professor" name="nm_professor">
                        </div>
                        <div class="col-md-2">
                            <a style="margin-top: 25px;" id="adicionar" class="btn btn-default" href="#"
                               title="Realizar inscrição do Professor">Adicionar Professor</a>
                        </div>
                    </div>
                </div>
            </form>
            <br/>
            <div id="realizarinscricoes-pagination"></div>
        </div>
    </div>
</div>
</div>
<script type="text/javascript" language="javascript" class="init">
    $(document).ready(function () {
        $("input#nm_professor").autocomplete({
            minLength: 3,
            source: "/professor-professor/autocompleteprofessor"
        });

        //Função que faz a listagem ser paginada.
        function carregarGridPaginadaAjax() {
            $.ajax({
                type: "post",
                dataType: "text",
                cache: false,
                url: '/banca_examinadora-bancaexaminadora/detalhe-pagination',
                async: true,
                data: {id_banca_examinadora: <?=$dados_banca['id_banca_examinadora']?>},
                beforeSend: function () {
                    $('#realizarinscricoes-pagination').html(
                        '<div class="row"><div class="col-md-12 text-center"><p><img src="/assets/img/carregando.gif"><p></div></div>'
                    );
                },
                success: function (data) {
                    $('#realizarinscricoes-pagination').html(data);
                }
            });
        }

        carregarGridPaginadaAjax(); //Chama a Paginação da listagem

        /*Função Ajax que adiciona os professores no Banco de dados*/
        $('#adicionar').click(function () {
            var dados = $('#form_realizar_inscricao').serialize();
            $.ajax({
                type: 'POST',
                dataType: 'json',
                url: '',
                async: true,
                data: dados,
                success: function (response) {
                    $("#nm_professor").val("");
                    $("#nm_professor").focus();
                    if (response.sucesso == true) {
                        $('#msg').html("<p>" + response.nm_professor + " foi <em>Inscrito(a) com sucesso!</em></p>");
                        $('#count').html(response.qtd_inscritos); // atualizando a quantidade de inscritos
                        carregarGridPaginadaAjax();
                        return;
                    } else if (response.sucesso == false && response.nm_professor == null) {
                        $('#msg').html("<p><em>Professor não encontrado!</em></p>");
                        return;
                    } else {
                        $('#msg').html("<p>" + response.nm_professor + " já <em> está nesta banca!</em></p>");
                        return;
                    }

                }
            });
            return false;
        });

        //Aciona o botão ADICIONAR, caso a tecla enter seja pressionada.
        $("#nm_professor").keypress(function (e) {
            if (e.which == 13) $("#adicionar").trigger('click');
        });

        //Colocar o foco no componente.
        $("#nm_professor").focus();

    });
</script>
