<div class="page-head">
    <h2>Cadastro</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="block-flat">
            <div class="content">
    <?php
    $form->setAttribute('action', $this->url('navegacao', array('controller'=>$controller,'action' => 'gravar')));
    $form->setAttribute('class', 'form-horizontal');
    $form->setAttribute('data-role', 'form');
    $form->prepare();
    echo $this->form()->openTag($form);
    $form->get('id')->setValue(Estrutura\Helpers\Cript::enc($form->get('id')->getValue())); 
    echo $this->formHidden($form->get('id'));

    #Customização para Trazer todas as Actions
    $id_action =  $form->get('id_action')->getValue();
    ?>
                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('id_perfil'))?>
                    </div>
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('id_modulo'))?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-10">
                        <label for="id_action">Selecione a Action</label><br />
                        <?php
                        #Recuperando todas as actions
                        $myAction = new \Action\Service\ActionService();
                        $arrAction = $myAction->fetchAll()->toArray();
                        foreach($arrAction as $key => $valor){ ?>
                            <input type="checkbox" name="id_action[]" id="id_action<?=$valor['id_action']?>" value="<?=$valor['id_action']?>" <?= $valor['id_action'] == $id_action ? "checked='checked'" : "" ?>  >
                            <?=$valor['nm_action']?>&nbsp;&nbsp;&nbsp;
                            <br />
                        <?php } ?>
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-md-10">
                        <button type="submit" class="btn btn-primary">Salvar</button>
                        <a href="<?=$this->url('navegacao', ['controller'=>$controller])?>" class="btn btn-default">Voltar</a>
                    </div>
                </div>saco
                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>