<?php
  /** @var $lista \Principal\Service\Principal[] */
?>
<div class="page-head">
    <div class="container">
        <div align="center">
            <h3>Navegaçao Rápida</h3>
            <p>Escolha pra onde deseja ir.</p>
        </div>
    </div>
    <?php //echo $this->Auth()->nm_usuario; ?>
    <?php //echo $this->Auth()->id_usuario; ?>
    <br /><br />
    <div class="form-group">
        <div class="col-sm-3">
            <button class="btn btn-primary" id="competicao">Competição</button>
        </div>
        <div class="col-sm-3">
            <button class="btn btn-primary" id="academias">Academias</button>
        </div>
        <div class="col-sm-3">
            <button class="btn btn-primary" id="inscricao">Inscrição no Evento</button>
        </div>
        <div class="col-sm-3">
            <button class="btn btn-primary" id="chavesdeluta">Chaves das Lutas</button>
        </div>
    </div>
</div>

<br /><br /><br /><br /><br /><br /><br /><br /><br />



<script type="text/javascript" language="javascript" class="init">
    $(document).ready(function() {
        $('#competicao').click(function(){
            href = 'evento-evento';
            window.location.href = href;
        });
        $('#academias').click(function(){
            href = 'academia-academia';
            window.location.href = href;
        });
        $('#inscricao').click(function(){
            href = 'inscricoes_evento-inscricoesevento';
            window.location.href = href;
        });
        $('#chavesdeluta').click(function(){
            href = 'chaves_luta-chavesluta';
            window.location.href = href;
        });
    });
</script>