<?php
/** @var $lista \Principal\Service\Principal[] */
?>
<div class="page-head">
    <br/><br/><br/><br/><br/>
    <div class="container">
        <div align="center">
            <img src="/assets/img/logo/logo-etec.png" max-width=" 200px" height="200px"/>
<!--                            <h2><font color="#006699">Escola de Tecnologia</font></h2>-->
<!--                        <p>Escolha pra onde deseja ir.</p>-->
        </div>
    </div>
    <?php //echo $this->Auth()->nm_usuario; ?>
    <?php //echo $this->Auth()->id_usuario; ?>
    <br/>

</div>

<br/><br/><br/>


