<div class="page-head">
    <h2>Alteraçao</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="block-flat">
            <div class="content">
            <?php
              $form->setAttribute('action', $this->url('navegacao',
                  array('controller'=>$controller,'action' => 'gravaralteracaoviaacademia')));
              $form->setAttribute('class', 'form-horizontal');
              $form->setAttribute('data-role', 'form');
              $form->prepare();
              echo $this->form()->openTag($form);

              # Recuperando todas as titulações
              $titulacao = new Titulacao\Service\TitulacaoService();
              $arrTitulacao = $titulacao->fetchAll()->toArray();
            ?>
                <div class="form-group">
                    <div class="col-md-4">
                        <input type="hidden" class="form-control" id="id_professor"
                            name="id_professor" value="<?= $id_professor ?>" />
                        <input type="hidden" class="form-control" id="id_usuario"
                            name="id_usuario" value="<?= $this->Auth()->id_usuario ?>" />
                        <input type="hidden" class="form-control" id="id_banca_examinadora"
                            name="id_banca_examinadora" value="<?= $id_banca_examinadora ?>" />
                        <input type="hidden" class="form-control" id="professor_cs_orientador"
                            name="professor_cs_orientador" value="<?= $professor_cs_orientador ?>" />
                        <input type="hidden" class="form-control" id="id_membro_banca"
                            name="id_membro_banca" value="<?= $id_membro_banca ?>" />
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                        <label for="nm_professor">Professor</label><br />
                        <input type="text" class="form-control" id="nm_professor" name="nm_professor"
                            value="<?= $nm_professor ?>" />
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                      <label for="nm_atleta">Titulação</label><br />
                      <select id="id_titulacao" class="form-control"
                        data-error="Campo é obrigatório." required="required"
                        data-source="arrId_titulacao" data-ng-options="k as v for (k,v) in arrId_titulacao"
                        name="id_titulacao">
                          <option value="">Selecione...</option>
                          <?php foreach ($arrTitulacao as $key => $value) { ?>
                                  <?php if ($id_titulacao == $value['id_titulacao']) { ?>
                                            <option value="<?= $value['id_titulacao'] ?>"
                                              selected><?= $value['nm_titulacao'] ?></option>
                                  <?php } else { ?>
                                            <option value="<?= $value['id_titulacao'] ?>">
                                                <?= $value['nm_titulacao'] ?></option>
                                  <?php } ?>
                          <?php } ?>
                      </select>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                        <label for="cs_ativo">Situação</label><br />
                        <select id="cs_ativo" class="form-control" data-source="arrCs_ativo"
                          data-ng-options="k as v for (k,v) in arrCs_ativo" name="cs_ativo">
                          <?php if($cs_ativo == 'A'){ ?>
                                  <option value="A" selected>Ativo</option>
                                  <option value="I">Inativo</option>
                          <?php } else if($cs_ativo == 'I') {?>
                                  <option value="A">Ativo</option>
                                  <option value="I" selected>Inativo</option>
                          <?php }?>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                        <label for="membro_cs_orientador">Este professor é orientador?</label><br />
                        <input type="hidden" name="membro_cs_orientador" id="membro_cs_orientador" value="N" />
                        <?php if($membro_cs_orientador == 'S'){ ?>
                                <input id="membro_cs_orientador" class="pop form-control"
                                  type="checkbox" checked="checked" value='S' name="membro_cs_orientador">
                        <?php } else if($membro_cs_orientador == 'N') {?>
                                <input id="membro_cs_orientador" class="pop form-control"
                                  type="checkbox" value='S' name="membro_cs_orientador">
                        <?php }?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-10">
                        <button type="submit" class="btn btn-primary">Salvar</button>
                        <a href="<?=$this->url('navegacao', ['controller'=>'banca_examinadora-bancaexaminadora',
                            'action' => 'realizarinscricoes', 'id'=>Estrutura\Helpers\Cript::enc($id_banca_examinadora)])?>"
                              class="btn btn-default">Voltar</a>
                    </div>
                </div>
                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>
