<div class="page-head">
    <h2>Cadastro</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="block-flat">
            <div class="content">
                <?php
                $form->setAttribute('action', $this->url('navegacao', array('controller' => $controller, 'action' => 'gravar')));
                $form->setAttribute('class', 'form-horizontal');
                $form->setAttribute('data-role', 'form');
                $form->prepare();
                echo $this->form()->openTag($form);
                $form->get('id')->setValue(Estrutura\Helpers\Cript::enc($form->get('id')->getValue()));
                echo $this->formHidden($form->get('id'));


                ?>
                <div class="form-group">
                    <div class="col-md-4">
                        <?= $this->formRow($form->get('id_perfil')) ?>
                    </div>
                    <div class="col-md-4">
                        <?= $this->formRow($form->get('id_modulo')) ?>
                    </div>
                </div>


                <div class="row" id="lista-permissoes"></div>


                <div class="row_form">
                    <div class="col-md-12 ">
                        <div class="form-group">
                            <div class="col-md-12">
                                <?= $this->formRow($form->get('id_action')) ?>
                                <div class="help-block with-errors"></div>
                            </div>
                        </div>
                    </div>
                </div>





                <div class="form-group">
                    <div class="col-md-10">
                        <button type="submit" class="btn btn-primary">Salvar</button>
                        <a href="<?= $this->url('navegacao', ['controller' => $controller]) ?>" class="btn btn-default">Voltar</a>
                    </div>
                </div>
                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>
<script>
    $(function () {
        $.ajax({
            type: "post",
            dataType: "text",
            cache: false,
            url: '/permissao-permissao/listar-permissoes-acoes',
            async: true,
            data: {
            },
            beforeSend: function () {
                $('#lista-permissoes').html(
                    '<div class="row"><div class="col-md-12 text-center"><p><img src="/assets/img/carregando.gif"><p></div></div>'
                );
            },
            success: function (data) {

                $('#lista-permissoes').html(data);
            }
        });

    })
</script>