<div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
    <!--    <div class="list-group">        
            <a href="#" class="list-group-item active">Comunicados</a>
            <a href="#" class="list-group-item">Nenhum comunicado não lido</a>
        </div>-->
    <div class="list-group">
        <a class="list-group-item active">Conferência Online<br />De segunda a sexta às 22:30</a>
        <span class="list-group-item  text-center">
            <a href="http://<?= $configList['link_conferencia'] ?>" target="_blank" >
                <?= $configList['link_conferencia'] ?>
            </a>
        </span>
    </div>
    <div class="list-group">
        <a class="list-group-item active">Link de Cadastro</a>
        <span class="list-group-item text-center">
            <a href="/cadastro/<?= $auth->id_usuario ?>" target="_blank">mcnetwork.com.br/cadastro/<?= $auth->id_usuario ?></a>
        </span>
    </div>
    <div class="list-group">
        <a href="#" class="list-group-item active">Meus Ganhos (Bônus)</a>
        <span class="list-group-item">
            <table class="table table-bordered">                
                <tbody>
                    <?php
                    if (!empty($meusGanhosList)) {
                        foreach ($meusGanhosList as $meuGanho) {
                            $dataPagamento = \Estrutura\Helpers\Data::$mes[$meuGanho['dt_pagamento']];
                            ?>
                            <tr>
                                <td class="text-center">
                                    <?= ucfirst($dataPagamento); ?>:                                
                                    <b>R$ <?= \Estrutura\Helpers\Valor::reais($meuGanho['vl_pago']); ?></b>
                                </td>
                            </tr>
                            <?php
                        }
                        ?>
                        <?php
                    } else {
                        ?>
                        <tr>
                            <td colspan="3" class="text-center">
                                Não há ganhos no período.
                            </td>
                        </tr>
                        <?php
                    }
                    ?>
                </tbody>                
            </table>            

            <div class="row">
                <div class="col-sm-12"> 
                    <a id="btn_list_extrato1" class="pull-right" style="cursor: pointer;">Detalhes...</a>  
                </div>
            </div>
        </span>
    </div>
    <div class="list-group">
        <a href="#" class="list-group-item active">Conta</a>
        <span class="list-group-item">
            <div class="row">
                <div class="col-sm-12"> 
                    Saldo disponível: <b>R$ <?= $contratoEntity->getVlSaldo() ? \Estrutura\Helpers\Valor::reais($contratoEntity->getVlSaldo()) : '0,00' ?></b>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-sm-12"> 
                    <a id="btn_list_extrato2" class="pull-right" style="cursor: pointer;">Detalhes...</a>  
                </div>
            </div>
        </span>
    </div>
</div>