<div class="page-head">
    <h2>Cadastro</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="block-flat">
            <div class="content">
            <?php
            $form->setAttribute('action', $this->url('navegacao', array('controller'=>$controller,'action' => 'gravar')));
            $form->setAttribute('class', 'form-horizontal');
            $form->setAttribute('data-role', 'form');
            $form->prepare();
            echo $this->form()->openTag($form);
            $form->get('id')->setValue(Estrutura\Helpers\Cript::enc($form->get('id')->getValue()));
            $form->get('dt_evento')->setValue(Estrutura\Helpers\Data::converterDataBancoMySQL2Brazil($form->get('dt_evento')->getValue()));

            #Recuperando o Nome de Uma Cidade Pelo ID e Setando no Formulario
            $cidade = new \Cidade\Service\CidadeService();
            $arrCidade = $cidade->getCidadeToArray($form->get('id_cidade')->getValue());
            $form->setData(['id_cidade' => $arrCidade['nm_cidade']]);

            echo $this->formHidden($form->get('id'));
            ?>
                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('id_tipo_evento'))?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('id_regra_luta'))?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('nm_evento'))?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('id_cidade')) ?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('dt_evento'))?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('vl_inscricao_colorida'))?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('vl_inscricao_preta'))?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('bo_inativo'))?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-10">
                        <button type="submit" class="btn btn-primary">Salvar</button>
                        <a href="<?=$this->url('navegacao', ['controller'=>$controller])?>" class="btn btn-default">Voltar</a>
                    </div>
                </div>
                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" language="javascript" class="init">
    $(document).ready(function() {
        $( "#dt_evento" ).datepicker(
            { dateFormat: 'dd/mm/yy' }
        );
        $( "input#id_cidade" ).autocomplete({
            minLength: 4,
            source: "/cidade-cidade/autocompletecidade"
        });

    });
</script>
