<?php
/** @var $form \Academia\Form\Academia */
/** @var $dados_academia \Academia\Service\Academia[] */
/** @var $lista_atletas \Atleta\Service\Atleta[] */
?>
<div class="page-head">
    <h2>Realizar Inscrição no Evento</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="block-flat">
            <div class="content">
                <fieldset>
                    <legend>Dados do Evento</legend>
                        <?php if(isset($dados_evento) && $dados_evento){ ?>
                            <?php
                                $cidade = new \Cidade\Service\CidadeService();
                                $arrCidade = $cidade->getCidadeToArray($dados_evento['id_cidade']);
                                $estadoService = new \Estado\Service\EstadoService();
                                $arrEstado = $estadoService->getEstadoToArray($arrCidade['id_estado']);
                            ?>
                            <div class="bs-callout bs-callout-primary">
                                <ul class="primary">
                                    <li><b>Nº de Inscritos:</b> <?=count($lista_inscritos)?></li>
                                    <li><b>Evento:</b> <?=$dados_evento['nm_evento']?></li>
                                    <li><b>Local do Evento:</b> <?=isset($dados_evento['tx_endereco']) && $dados_evento['tx_endereco']?$dados_evento['tx_endereco']:'Nao informado'?></li>
                                    <li><b>Cidade:</b> <?=$arrCidade['nm_cidade'] . ' - ' . $arrEstado['nm_estado']?></li>
                                </ul>
                            </div>
                        <?php } ?>
                </fieldset>
                <form action="#" method="post" id="form_realizar_inscricao">
                    <div class="row">
                        <div class="form-group">
                            <div class="col-md-4">
                                <label for="nm_atleta">Escolha o Atleta</label>
                                <input type="text" value="" data-error="Campo é obrigatório." required="required" class="form-control" id="nm_atleta" name="nm_atleta">
                                <div id="msg"></div>
                                <input type="hidden" class="form-control" id="id_evento" name="id_evento" value="<?= $dados_evento['id_evento']?>"><br />
                                <a id="salvar" class="btn btn-default" href="#" title="Realizar inscrição do Atleta">Inscrever Atleta</a>
                            </div>
                        </div>
                    </div>
                </form>
                <br />
                <table class="table table-bordered dataTable">
                    <thead>
                    <tr>
                        <th>Atleta</th>
                        <th>Sexo</th>
                        <th>Peso</th>
                        <th>Idade</th>
                        <th>Ações</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php $sexo = new \Sexo\Service\SexoService(); ?>
                    <?php $atleta = new \Atleta\Service\AtletaService(); ?>
                    <?php $academia = new \Academia\Service\AcademiaService(); ?>
                    <?php $cidade = new \Cidade\Service\CidadeService(); ?>
                    <?php $estado = new \Estado\Service\EstadoService(); ?>
                    <?php foreach($lista_inscritos as $item){ ?>
                        <?php $obAltleta = $atleta->buscar($item->getIdAtleta()); ?>
                        <?php $obAcademia = $academia->buscar($obAltleta->getIdAcademia()); ?>
                        <?php $obCidade = $cidade->buscar($obAcademia->getIdCidade()); ?>
                        <?php $obEstado = $estado->buscar($obCidade->getIdEstado()); ?>
                        <?php $aobSexo = $sexo->buscar($obAltleta->getIdSexo()); ?>
                        <tr>
                            <td><?=$obAltleta->getNmAtleta() . ' (' . $obAcademia->getNmAcademia() . $obCidade->getNmCidade() . ', ' . $obEstado->getNmEstado() . ')'?></td>
                            <td><?=$aobSexo->getNmSexo()?></td>
                            <td><?=$obAltleta->getNrPeso().' Kg'?></td>
                            <td><?=(\Estrutura\Helpers\Data::calcularIdadeDoAtleta($obAltleta->getDtNascimento()) - 1) .' Anos'?></td>

                            <td style="width: 180px;">
                                <?=\Estrutura\Service\HtmlHelper::botaoAlterar($this->url('navegacao',array('controller'=>'atleta-atleta','action'=>'alterarviaacademia','id'=>$item->getId() )))?>
                                <?=\Estrutura\Service\HtmlHelper::botaoExcluir($this->url('navegacao',array('controller'=>'atleta-atleta','action'=>'excluirviaacademia','id'=>$item->getId() )))?>
                            </td>
                        </tr>
                    <?php }; ?>
                    </tbody>
                </table>
                <div class="row">
                    <div class="form-group">
                        <div class="col-md-10">
                            <a class="btn btn-default" href="<?=$this->url('navegacao',array('controller'=>$controller,'action'=>'cadastro'))?>" title="Realizar Inscrição de Atletas">Nova Inscrição</a>
                            <a href="<?=$this->url('navegacao', ['controller'=>$controller])?>" class="btn btn-default">Voltar</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" language="javascript" class="init">
    $(document).ready(function() {
        $( "input#nm_atleta" ).autocomplete({
            minLength: 3,
            source: "/atleta-atleta/autocompleteatleta"
        });

        $('#salvar').click(function() {
            var dados = $('#form_realizar_inscricao').serialize();
            $.ajax({
                type: 'POST',
                dataType: 'json',
                url: '',
                async: true,
                data: dados,
                success: function(response) {
                    $("#nm_atleta").val("");
                    $("#nm_atleta").focus();
                    if(response.sucesso == true){
                        $('#msg').html( "<p>O Atleta " + response.nm_atleta + " foi <em>Inscrito(a) com sucesso!</em></p>" );
                    } else{
                        $('#msg').html( "<p>O Atleta " + response.nm_atleta + " já <em> Consta na Base de Dados!</em></p>" );
                    }

                }
            });

            return false;
        });

    });
</script>