<?php
  /** @var $form \Graduacao\Form\Graduacao */
  /** @var $lista \Graduacao\Service\Graduacao[] */
?>
<div class="page-head">
    <h2>Lista de Graduações</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="col-md-12">
            <a class="btn btn-default" href="<?=$this->url('navegacao',array('controller'=>$controller,'action'=>'cadastro'))?>" title="Inserir uma nova graduação ao sistema">Nova Graduação</a>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-12">
            <div class="block-flat">
                <div class="content">

                    <table class="table table-bordered dataTable">
                        <thead>
                            <tr>
                                <th>Arte Marcial</th>
                                <th>Estilo</th>
                                <th>Graduacao</th>

                                <th>Ações</th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php $arteMarcialService = new \ArteMarcial\Service\ArteMarcialService(); ?>
                        <?php foreach($lista as $item){ ?>
                            <?php
                            $arArteMarcial = $arteMarcialService->getArteMarcialtoArray($item->getIdArteMarcial());

                            $estiloService = new \Estilo\Service\EstiloService();
                            $arEstilo = $estiloService->getEstiloToArray($item->getIdEstilo());
                            ?>
                            <tr>
                                <td><?=$arArteMarcial['nm_arte_marcial']?></td>
                                <td><?=$arEstilo['nm_estilo']?></td>
                                <td align="center"><img alt="<?=$item->getNmGraduacao()?>" height="42" width="42" src="/assets/img/graduacoes/<?=$item->getNmGraduacao()?>.jpeg" /><br /><?=$item->getNmGraduacao()?></td>

                                <td style="width: 150px;">
                                    <?=\Estrutura\Service\HtmlHelper::botaoAlterar($this->url('navegacao',array('controller'=>$controller,'action'=>'cadastro','id'=>Estrutura\Helpers\Cript::enc($item->getId()))))?>
                                    <?=\Estrutura\Service\HtmlHelper::botaoExcluir($this->url('navegacao',array('controller'=>$controller,'action'=>'excluir','id'=>Estrutura\Helpers\Cript::enc($item->getId()))))?>
                                </td>
                            </tr>
                        <?php }; ?>
                        </tbody>
                    </table>
                    <div class="row">
                        <div class="col-md-12">
                            <a href="<?=$this->url('navegacao', ['controller'=>'principal-principal'])?>" class="btn btn-primary" title="Retorna para a Página Principal">Home</a>
                        </div>
                    </div>
                    <?php //echo $this->paginationControl($lista, 'Sliding', 'partial/paginator', array('route'=>'graduacao/paginator')); ?>
                </div>
            </div>
        </div>
    </div>    
</div>
