<div class="page-head">
    <h2>Listaxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="col-md-12">
            <a class="btn btn-default" href="<?=$this->url('navegacao',array('controller'=>$controller,'action'=>'cadastro'))?>">Novo</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="block-flat">
                <div class="content">

                    <table class="table table-bordered dataTable">
                        <thead>
                            <tr>
                                <th>Arte Marcial</th>
                                <th>Estilo</th>

                                <th>Ações</th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php $arteMarcialService = new \ArteMarcial\Service\ArteMarcialService(); ?>
                            <tr>
                                <td><?=$abc?></td>
                                <td><?=$def?></td>

                                <td style="width: 150px;">
                                    <?=\Estrutura\Service\HtmlHelper::botaoAlterar($this->url('navegacao',array('controller'=>$controller,'action'=>'cadastro','id'=>Estrutura\Helpers\Cript::enc($item->getId()))))?>
                                    <?=\Estrutura\Service\HtmlHelper::botaoExcluir($this->url('navegacao',array('controller'=>$controller,'action'=>'excluir','id'=>Estrutura\Helpers\Cript::enc($item->getId()))))?>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <?php //echo $this->paginationControl($lista, 'Sliding', 'partial/paginator', array('route'=>'graduacao/paginator')); ?>
                </div>
            </div>
        </div>
    </div>    
</div>
