<footer>
    <div class="row">
        <div class="col-md-2">&nbsp;</div>
        <div class="col-md-8 text-center">
            <a href="#" data-toggle="modal" data-target="#myModalPoliticas">Política de Privacidade</a> | <a href="#" data-toggle="modal" data-target="#myModalTermos">Termos de Utilização</a> | <a href="#" data-toggle="modal" data-target="#myModalDeclaracao">Declaração de Segurança</a>
            <br>
            <img src="/assets/img/logo/logo-menu.png" />
        </div>
        <div class="col-md-2">&nbsp;</div>
    </div>
    <br>    
</footer>

<!-- Modal -->
<div class="modal fade" id="myModalPoliticas" tabindex="-1" role="dialog" aria-labelledby="myModalPoliticasLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalPoliticasLabel">Política de Privacidade</h4>
            </div>
            <div class="modal-body">

                <h3> Política de Privacidade </h3>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModalTermos" tabindex="-1" role="dialog" aria-labelledby="myModalTermosLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalTermosLabel">Termos de Utilização</h4>
            </div>
            <div class="modal-body">

                <h3> Termos de Utilização </h3>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModalDeclaracao" tabindex="-1" role="dialog" aria-labelledby="myModalDeclaracaoLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalDeclaracaoLabel">Declaraçao de Segurança</h4>
            </div>
            <div class="modal-body">

                <h3> Declaraçao de Segurança</h3>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>
