<link rel="stylesheet" href="/assets/compact-css/jquery.tablesorter.theme.bootstrap.css,jquery.tablesorter.pager.css">


<div class="page-head">
    <h2>Campo para Pesquisar TCC</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="col-md-12">
            <a class="btn btn-default" href="<?=$this->url('navegacao',array('controller'=>$controller,'action'=>'pesquisar'))?>" >Pesquisar</a>
        </div>
    </div>
    <br />
    <div class="row" id="pesquisar"></div>
</div>

<script>
    $(function () {

        $.ajax({
            type: "post",
            dataType: "text",
            cache: false,
            url: '/pesquisar-pesquisar/index-pagination',
            async: true,
            data: {
            },
            beforeSend: function () {

                $('#pesquisar').html(
                    '<div class="row"><div class="col-md-12 text-center"><p><img src="/assets/img/carregando.gif"><p></div></div>'
                );
            },
            success: function (data) {

                $('#pesquisar').html(data);
            }
        });

    })
</script>
