<?php
/** @var $lista \Pesquisar\Service\Pesquisar[] */
?>
<div class="page-head">
    <?php //echo $this->Auth()->nm_usuario; ?>
    <?php //echo $this->Auth()->id_usuario; ?>
    <br/>
    <div class="block-flat">
        <div class="content">
            <div class="panel panel-primary">
                <div class="panel-heading">Dados para Pesquisa</div>
                <div class="panel-body" style="background-color: #F7F7F7">



                </div>
            </div>
        </div>
        <?= $this->form()->closeTag(); ?>
    </div>
</div>

<div class="cl-mcont">

</div>

<br/><br/><br/>


