<link rel="stylesheet" href="/assets/compact-css/jquery.tablesorter.theme.bootstrap.css,jquery.tablesorter.pager.css">

<div class="col-md-12">
    <div class="table-responsive">
        <table class="table table-striped" id="tablesorterTcc" >
            <thead>
            <tr>
                <th class="text-center">Professor</th>
                <th class="text-center">Curso</th>
                <th class="text-center">Tipo</th>
                <th class="text-center">Área de Conhecimento</th>
                <th class="text-center">Data da Banca</th>
                <th class="text-center">Nome do concluinte</th>
                <th class="text-center">Palavra Chave</th>
                <th class="text-center">Download</th>
                <th class="text-center">Ações</th>
            </tr>
            </thead>
            <tfoot>
            <tr>
                <th class="text-center">Professor</th>
                <th class="text-center">Curso</th>
                <th class="text-center">Tipo</th>
                <th class="text-center">Área de Conhecimento</th>
                <th class="text-center">Data da Banca</th>
                <th class="text-center">Nome do concluinte</th>
                <th class="text-center">Palavra Chave</th>
                <th class="text-center">Download</th>
                <th class="text-center">Ações</th>
            </tr>
            <tr>
                <th colspan="7" class="ts-pager form-horizontal">
                    <?php
                    echo $this->paginationControl(
                        $paginator, 'Sliding', 'partials/pagination.phtml', [
                            'urlPagination' => 'pesquisar-pesquisar/index-pagination',
                            'countPerPage' => $countPerPage,
                            'divData' => '#pesquisar',
                        ]
                    );
                    ?>
                </th>

            </tr>

            </tfoot>
            <?php
            $numeroLinha = (($paginator->getCurrentPageNumber() - 1) * $paginator->getItemCountPerPage());
            if (!empty($paginator)) {
                ?>
                <tbody class="" align="center">
                <tr role="row" class="tablesorter-filter-row">
                    <?php
                    foreach ($camposFilter as $key => $campoFilter) {
                        ?>
                        <td style="background-color: #e3e3e3;">
                            <?php
                            if (!is_null($campoFilter)) {
                                ?>
                                <input type="search" placeholder="" class="tablesorter-filter" data-column="<?= $key ?>" value="<?= isset($filter[$key]) ? $filter[$key] : '' ?>">
                                <?php
                            } else {
                                ?>
                                &nbsp;
                                <?php
                            }
                            ?>
                        </td>
                        <?php
                    }
                    ?>
                </tr>
                <?php
                foreach ($paginator as $item) {
                    ?>
                    <tr>
                        <td><?= $item['id_tcc']?></td>
                        <td class="text-center"><?= \Estrutura\Helpers\String::nomeMaiusculo($item['nm_professor']) ?></td>
                        <td class="text-center"><?= \Estrutura\Helpers\String::nomeMaiusculo($item['nm_curso']) ?></td>
                        <td class="text-center"><?= \Estrutura\Helpers\String::nomeMaiusculo($item['nm_tipo_tcc']) ?></td><td class="text-center"><?=Estrutura\Helpers\Data::converterDataBancoMySQL2Brazil($item['dt_banca']) ?></td>
                        <td class="text-center"><?= \Estrutura\Helpers\String::nomeMaiusculo($item['nm_area_conhecimento']) ?></td>
                        <td class="text-center"><?= \Estrutura\Helpers\Data::converterDataBancoMySQL2Brazil($item['id_banca_examinadora']) ?></td>
                        <td class="text-center"><?= \Estrutura\Helpers\String::nomeMaiusculo($item['nm_concluinte']) ?></td>
                        <td class="text-center"><?= \Estrutura\Helpers\String::nomeMaiusculo($item['nm_palavra_chave']) ?></td>
                        <td class="text-center">

                            <?php if(is_null($item['ar_arquivo'])) { ?>
                                &nbsp;
                            <?php } else {  ?>
                                <?= \Estrutura\Service\HtmlHelper::botaoDownload(
                                    $this->url('navegacao', array('controller' => $controller, 'action' => 'download-arquivo', 'id' => \Estrutura\Helpers\Cript::enc($item['id_tcc']))),
                                    'Download',
                                    'enviar_para_download',
                                    'glyphicon glyphicon-cloud-download',
                                    'btn-alterar btn-xs btn-alterar-customizado'
                                ) ?>
                            <?php } ?>
                        </td>
                        <td style="width: 180px;">


                        </td>
                    </tr>
                    <?php
                }
                ?>
                </tbody>
                <?php
            }
            ?>

        </table>
        <div class="row">
            <div class="col-md-12">
                <a href="<?= $this->url('navegacao', ['controller' => 'principal-principal']) ?>" class="btn btn-primary" title="Retorna para a Página Principal">Home</a>

            </div>
        </div>
    </div>
</div>
<!--<script src="/assets/compact-js/moment.js,validator.min.js,jquery.mask.min.js,jquery.ui.widget.js,jquery.tablesorter.js,jquery.tablesorter.widgets.js,jquery.tablesorter.pager.js" type="text/javascript"></script>-->
<script src="/assets/js/moment.js" type="text/javascript"></script>
<script src="/assets/js/validator.min.js" type="text/javascript"></script>
<script src="/assets/js/jquery.mask.min.js" type="text/javascript"></script>
<script src="/assets/js/jquery.ui.widget.js" type="text/javascript"></script>
<script src="/assets/js/jquery.tablesorter.js" type="text/javascript"></script>
<script src="/assets/js/jquery.tablesorter.widgets.js" type="text/javascript"></script>
<script src="/assets/js/jquery.tablesorter.pager.js" type="text/javascript"></script>

<script type="text/javascript" language="javascript" class="init">
    $(document).ready(function () {
        $("input#nm_professor").autocomplete({
            minLength: 3,
            source: "/professor-professor/autocompleteprofessor"
        });
    });
    $(document).ready(function () {
        $("input#nm_concluinte").autocomplete({
            minLength: 3,
            source: "/concluinte-concluinte/autocompleteconcluinte"
        });
    });
</script>