<link rel="stylesheet" href="/assets/compact-css/jquery.tablesorter.theme.bootstrap.css,jquery.tablesorter.pager.css">

<!--<link rel="stylesheet" href="/assets/css/jquery.tablesorter.theme.bootstrap.css">-->
<!--<link rel="stylesheet" href="/assets/css/jquery.tablesorter.pager.css">-->


<?php
/** @var $form \Curso\Form\Curso */
/** @var $lista \Curso\Service\Curso[] */
?>
<div class="page-head">
    <h2>Lista de Cursos</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="col-md-12">
            <a class="btn btn-default" href="<?= $this->url('navegacao', array('controller' => $controller, 'action' => 'cadastro')) ?>" title="Adicionar um novo Curso">Novo Curso</a>
        </div>
    </div>
    <br />
    <div class="row" id="curso-pagination"></div>    
</div>

<script>
    $(function () {

        $.ajax({
            type: "post",
            dataType: "text",
            cache: false,
            url: '/curso-curso/index-pagination',
            async: true,
            data: {
            },
            beforeSend: function () {

                $('#curso-pagination').html(
                        '<div class="row"><div class="col-md-12 text-center"><p><img src="/assets/img/carregando.gif"><p></div></div>'
                        );
            },
            success: function (data) {

                $('#curso-pagination').html(data);
            }
        });

    })
</script>
