<?php
  /** @var $form \CategoriaIdade\Form\CategoriaIdade */
  /** @var $lista \CategoriaIdade\Service\CategoriaIdade[] */
?>
<div class="page-head">
    <h2>Lista de Categorias de Idade</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="col-md-12">
            <a class="btn btn-default" href="<?=$this->url('navegacao',array('controller'=>$controller,'action'=>'cadastro'))?>" title="Inserir uma vova categoria de idade">Nova Categoria</a>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-12">
            <div class="block-flat">
                <div class="content">

                    <table class="table table-bordered dataTable">
                        <thead>
                            <tr>
                                <th>Categoria de Idade</th>
                                <th>Sugestao de Idade Inicial</th>
                                <th>Sugestao de Idade Final</th>

                                <th>Ações</th>
                            </tr>
                        </thead>
                        <tbody>

                        <?php foreach($lista as $item){ ?>
                            <tr>
                                <td><?=$item->getNmCategoriaIdade()?></td>
                                <td><?=$item->getNrSugestaoIdadeInicial() . ' Anos'?></td>
                                <td><?=$item->getNrSugestaoIdadeFinal(). ' Anos'?></td>

                                <td style="width: 150px;">
                                    <?=\Estrutura\Service\HtmlHelper::botaoAlterar($this->url('navegacao',array('controller'=>$controller,'action'=>'cadastro','id'=>Estrutura\Helpers\Cript::enc($item->getId()))))?>
                                    <?=\Estrutura\Service\HtmlHelper::botaoExcluir($this->url('navegacao',array('controller'=>$controller,'action'=>'excluir','id'=>Estrutura\Helpers\Cript::enc($item->getId()))))?>
                                </td>
                            </tr>
                        <?php }; ?>
                        </tbody>
                    </table>
                    <div class="row">
                        <div class="col-md-12">
                            <a href="<?=$this->url('navegacao', ['controller'=>'principal-principal'])?>" class="btn btn-primary" title="Retorna para a Página Principal">Home</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>    
</div>
<script type="text/javascript" language="javascript" class="init">
    $(document).ready(function() {

    });
</script>