<?php
  /** @var $form \Academia\Form\Academia */
  /** @var $lista \Academia\Service\Academia[] */
?>
<div class="page-head">
    <h2>Lista de Academias</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="col-md-12">
            <a class="btn btn-default" href="<?=$this->url('navegacao',array('controller'=>$controller,'action'=>'cadastro'))?>" title="Adicionar Academia">Nova Academia</a>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-12">
            <div class="block-flat">
                <div class="content">
                    <table id="grid-basic" class="table table-condensed table-hover table-striped">
<!--                    <table id="grid-data" class="table table-condensed table-hover table-striped">-->
<!--                    <table class="table table-bordered dataTable">-->
                        <thead>
                            <tr>
                                <th>Nome da Academia</th>
                                <th>Cidade</th>

                                <th>Ações</th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php $cidade = new \Cidade\Service\CidadeService(); ?>
                        <?php $estado = new \Estado\Service\EstadoService(); ?>
                        <?php foreach($lista as $item){ ?>
                            <tr>
                                <td><?=$item->getNmAcademia()?></td>
                                <td>
                                    <?php $arrCidade = $cidade->getCidadeToArray($item->getIdCidade()); ?>
                                    <?php $arrEstado = $estado->getEstadoToArray($arrCidade['id_estado']); ?>
                                    <?=$arrCidade['nm_cidade'] . ' - ' . $arrEstado['sg_estado']?>
                                </td>

                                <td style="width: 180px;">
                                    <?=\Estrutura\Service\HtmlHelper::botaoAlterarCustomizado($this->url('navegacao',array('controller'=>$controller,'action'=>'cadastrocustomizado','id'=>Estrutura\Helpers\Cript::enc($item->getId()))),'Adicionar Atletas')?>
                                    <?=\Estrutura\Service\HtmlHelper::botaoAlterar($this->url('navegacao',array('controller'=>$controller,'action'=>'cadastro','id'=>Estrutura\Helpers\Cript::enc($item->getId()))))?>
                                    <?=\Estrutura\Service\HtmlHelper::botaoExcluir($this->url('navegacao',array('controller'=>$controller,'action'=>'excluir','id'=>Estrutura\Helpers\Cript::enc($item->getId()))))?>
                                </td>
                            </tr>
                        <?php }; ?>
                        </tbody>
                    </table>
                    <div class="row">
                        <div class="col-md-12">
                            <a href="<?=$this->url('navegacao', ['controller'=>'principal-principal'])?>" class="btn btn-primary" title="Retorna para a Página Principal">Home</a>
                            <a class="btn btn-default" href="<?=$this->url('navegacao',array('controller'=>$controller,'action'=>'cadastro'))?>" title="Adicionar Academia">Nova Academia</a>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>    
</div>
<script type="text/javascript" language="javascript" class="init">
    $(document).ready(function() {
        $("#grid-basic").bootgrid();
    });
</script>

