<div class="page-head">
    <h2>Cadastro Periodo Letivo</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="block-flat">
            <div class="content">
                <fieldset>
                    <legend>Dados do Periodo Letivo</legend>
                    <?php if(isset($dadosPeriodoLetivo) && $dadosPeriodoLetivo){ ?>
                        <div class="bs-callout bs-callout-primary">
                            <ul class="primary">
                                <li><b>Codigo Periodo:</b> <?=$dadosPeriodoLetivo->getId()?></li>
                                <li><b>Periodo Letivo:</b> <?=$dadosPeriodoLetivo->getDtAnoLetivo()?></li>
                                <li><b>Data de Inicio:</b> <?=$dadosPeriodoLetivo->getDtInicio()?></li>
                                <li><b>Data de termino:</b> <?=$dadosPeriodoLetivo->getDtFim()?></li>
                            </ul>
                        </div>
                    <?php } ?>
                </fieldset>
                <?php
                $form->setAttribute('action', '#');
                $form->setAttribute('class', 'form-horizontal');
                $form->setAttribute('method', 'post');
                $form->setAttribute('data-role', 'form');

                $form->prepare();
                echo $this->form()->openTag($form);
                $form->get('id')->setValue($dadosPeriodoLetivo->getId());
                $form->get('dt_encontro')->setValue(Estrutura\Helpers\Data::converterDataBancoMySQL2Brazil($form->get('dt_encontro')->getValue()));
                echo $this->formHidden($form->get('id'));
                ?>

                <div class="form-group">
                    <div class="col-md-7">
                        <div class="input-group" id="datetimepicker">
                            <?= $this->formRow($form->get('dt_encontro')); ?></br>
                            <a id="adicionar" class="btn btn-default" href="#" title="Adicionar data do encontro">Adicionar Encontro</a>
                        </div>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-10">
<!--                        <button type="submit" class="btn btn-primary">Salvar</button>-->
                        <a class="btn btn-default" href="<?=$this->url('navegacao',array('controller'=>$controller,'action'=>'cadastro', 'id'=>Estrutura\Helpers\Cript::enc($dadosPeriodoLetivo->getId())))?>" title="Voltar">Voltar</a>
                        <a href="<?=$this->url('navegacao', ['controller'=>$controller])?>" class="btn btn-default">Lista de Periodo Letivo</a>
                    </div>
                </div>
                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
    <div class="row" id="periodoletivodetalhe-pagination"></div>
</div>
<script type="text/javascript" src="/assets/compact-js/moment.js,bootstrap-datetimepicker.min.js,validator.min.js,jquery.mask.min.js,jquery.complexify.js,usuario|usuario|cadastro.js"></script>
<script type="text/javascript" language="javascript" class="init">
    $(document).ready(function() {
        $( "#dt_encontro" ).datepicker(
            { dateFormat: 'dd/mm/yy' }
        );

        //Função que faz a listagem ser paginada.
        function carregarGridPaginadaAjax(){
                $.ajax({
                    type: "post",
                    dataType: "text",
                    cache: false,
                    url: '/periodo_letivo-periodoletivo/detalhe-pagination',
                    async: true,
                    data: { id_periodo_letivo : <?=$dadosPeriodoLetivo->getId()?>},
                    beforeSend: function () {
                        $('#periodoletivodetalhe-pagination').html(
                            '<div class="row"><div class="col-md-12 text-center"><p><img src="/assets/img/carregando.gif"><p></div></div>'
                        );
                    },
                    success: function (data) {
                        $('#periodoletivodetalhe-pagination').html(data);
                    }
                });
        }
        carregarGridPaginadaAjax(); //Chama a Paginação da listagem

        /*Função Ajax que adiciona os encontros ao Banco de dados*/
        $('#adicionar').click(function() {
            var dados = $('#detalheperiodoletivoform').serialize();
            $.ajax({
                type: 'POST',
                dataType: 'json',
                url: '/periodo_letivo-periodoletivo/adicionarperiodoletivodetalhe',
                async: true,
                data: dados,
                success: function(response) {
                    $("#dt_encontro").val("");
                    if(response.sucesso == true){
                        carregarGridPaginadaAjax();
                    }
                }
            });

            return false;
        });

    });
</script>
