<div class="page-head">
    <h2>Cadastro Periodo Letivo</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="block-flat">
            <div class="content">
                <?php


                $form->setAttribute('action', $this->url('navegacao', array('controller'=>$controller,'action' => 'gravar')));
                $form->setAttribute('class', 'form-horizontal');
                $form->setAttribute('method', 'post');
                $form->setAttribute('data-role', 'form');

                $form->prepare();
                echo $this->form()->openTag($form);
                $form->get('id')->setValue(Estrutura\Helpers\Cript::enc($form->get('id')->getValue()));
                $form->get('dt_inicio')->setValue(Estrutura\Helpers\Data::converterDataBancoMySQL2Brazil($form->get('dt_inicio')->getValue()));
                $form->get('dt_fim')->setValue(Estrutura\Helpers\Data::converterDataBancoMySQL2Brazil($form->get('dt_fim')->getValue()));

                echo $this->formHidden($form->get('id'));
                ?>

                <div class="form-group">
                    <div class="col-md-7">

                        <div class="input-group" id="datetimepicker">
                            <?= $this->formRow($form->get('dt_inicio')); ?>
                        </div>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-7">

                        <div class="input-group" id="datetimepicker">
                            <?= $this->formRow($form->get('dt_fim')) ?>
                        </div>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('dt_ano_letivo'))?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-10">
                        <button type="submit" class="btn btn-primary">Salvar</button>
                        <a href="<?=$this->url('navegacao', ['controller'=>$controller])?>" class="btn btn-default">Voltar</a>
                    </div>
                </div>
                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="/assets/compact-js/moment.js,bootstrap-datetimepicker.min.js,validator.min.js,jquery.mask.min.js,jquery.complexify.js,usuario|usuario|cadastro.js"></script>
<script type="text/javascript" language="javascript" class="init">
    $(document).ready(function() {
        $( "#dt_inicio" ).datepicker(
            { dateFormat: 'dd/mm/yy' }
        );
        $( "#dt_fim" ).datepicker(
            { dateFormat: 'dd/mm/yy' }
        );

    });
</script>
