
<?php
/**
 * @var $form \DetalhePeriodoLetivo\Form\DetalhePeriodo */

/** @var $lista \DetalhePeriodoLetivo\Service\DetalhePeriodo
 */

?>

<div class="page-head">
    <h2>Detalhe-Periodo</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="col-md-12">
            <a class="btn btn-default" href="<?=$this->url('navegacao',array('controller'=>$controller,'action'=>'cadastro'))?>" title="Novo Periodo Letivo">Cadastrar Detalhe Periodo-Letivo</a>
        </div>
    </div>
    <br />
    <div class="row" id="detalhe-periodo"></div>
</div>

<script>
    $(function () {

        $.ajax({
            type: "post",
            dataType: "text",
            cache: false,
            url: '/detalhe_periodo_letivo-detalheperiodoletivo/index-pagination',
            async: true,
            data: {
            },
            beforeSend: function () {

                $('#detalhe-periodo').html(
                    '<div class="row"><div class="col-md-12 text-center"><p><img src="/assets/img/carregando.gif"><p></div></div>'
                );
            },
            success: function (data) {

                $('#detalhe-periodo').html(data);
            }
        });

    })
</script>
