<div class="page-head">
    <h2>Cadastro</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="block-flat">
            <div class="content">
            <?php
            $form->setAttribute('action', $this->url('navegacao', array('controller'=>$controller,'action' => 'gravar')));
            $form->setAttribute('class', 'form-horizontal');
            $form->setAttribute('data-role', 'form');
            $form->prepare();
            echo $this->form()->openTag($form);
            $form->get('id')->setValue(Estrutura\Helpers\Cript::enc($form->get('id')->getValue()));
            $form->get('id_usuario_cadastro')->setValue($this->Auth()->id_usuario);

            echo $this->formHidden($form->get('id'));
            echo $this->formHidden($form->get('id_usuario_cadastro'));
            ?>
                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('id_regra_luta'))?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('id_categoria_idade'))?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('nr_idade_inicial'))?>
                    </div>
                    <div id="loadingDiv" style="float:left; margin-left:2px;border: 0;"><img src="/assets/img/images/loader.gif" alt="loading... wait"></div>
                </div>

                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('nr_idade_final'))?>
                    </div>
                    <div id="loadingDiv2" style="float:left; margin-left:2px;border: 0;"><img src="/assets/img/images/loader.gif" alt="loading... wait"></div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('id_categoria_peso'))?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('nr_peso_inicial'))?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('nr_peso_final'))?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('id_sexo'))?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('id_graduacao_inicial'))?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('id_graduacao_final'))?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-10">
                        <button type="submit" class="btn btn-primary">Salvar</button>
                        <a href="<?=$this->url('navegacao', ['controller'=>$controller])?>" class="btn btn-default">Voltar</a>
                    </div>
                </div>
                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" language="javascript" class="init">
    $(document).ready(function() {

        $('#loadingDiv').hide();
        $('#loadingDiv2').hide();
        $(document).ajaxStart(function() {
            $( "#loadingDiv" ).show();
            $( "#loadingDiv2" ).show();
        });
        $(document).ajaxStop(function() {
            $( "#loadingDiv" ).hide();
            $( "#loadingDiv2" ).hide();
        });

        $( "#id_categoria_idade" ).change(function() {
            var chave = $("#id_categoria_idade").val();
            //var texto = $("#id_categoria_idade option:selected").text();
            //The post using ajax
            $.ajax({
                type:"GET",
                url:"/categoria_idade-categoriaidade/carregarsugestaoidadeporcategoria?termo="+chave,
                data:null,
                success: function(data){
                    $("#nr_idade_inicial").val(data.nr_sugestao_idade_inicial);
                    $("#nr_idade_final").val(data.nr_sugestao_idade_final);
                },
                error : function(xhr, textStatus, errorThrown) {
                    if (xhr.status === 0) {
                        alert('Not connected. Verify Network.');
                    } else if (xhr.status == 404) {
                        alert('Requested page not found. [404]');
                    } else if (xhr.status == 500) {
                        alert('Server Error [500].');
                    } else if (errorThrown === 'parsererror') {
                        alert('Requested JSON parse failed.');
                    } else if (errorThrown === 'timeout') {
                        alert('Time out error.');
                    } else if (errorThrown === 'abort') {
                        alert('Ajax request aborted.');
                    } else {
                        alert('Remote sever unavailable. Please try later');
                    }
                }
            });
        });
    });
</script>
