<?php
  /** @var $form \DetalhesRegrasLuta\Form\DetalhesRegrasLuta */
  /** @var $lista \DetalhesRegrasLuta\Service\DetalhesRegrasLuta[] */
?>
<div class="page-head">
    <h2>Lista de Configurações de Luta</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="col-md-12">
            <a class="btn btn-default" href="<?=$this->url('navegacao',array('controller'=>$controller,'action'=>'cadastro'))?>">Nova Configuração</a>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-12">
            <div class="block-flat">
                <div class="content">

                    <table class="table table-bordered dataTable">
                        <thead>
                            <tr>
                                <th>Regra</th>
                                <th>Categoria de Idade</th>
                                <th>Sexo</th>
                                <th>Categoria de Peso</th>
                                <th>Graduaçao Inicial</th>
                                <th>Graduaçao Final</th>

                                <th>Ações</th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php $graduacao = new \Graduacao\Service\GraduacaoService(); ?>
                        <?php $regras_lutas = new \RegrasLutas\Service\RegrasLutasService(); ?>
                        <?php $categoria_peso = new \CategoriaPeso\Service\CategoriaPesoService(); ?>
                        <?php $categoria_idade = new \CategoriaIdade\Service\CategoriaIdadeService(); ?>
                        <?php $sexo = new \Sexo\Service\SexoService(); ?>
                        <?php foreach($lista as $item){ ?>
                            <?php $arrRegrasLutas = $regras_lutas->getRegrasLutasToArray($item->getIdRegraLuta()); ?>
                            <?php $arrGraduacaoInicial = $graduacao->getGraduacaoToArray($item->getIdGraduacaoInicial()); ?>
                            <?php $arrGraduacaoFinal = $graduacao->getGraduacaoToArray($item->getIdGraduacaoFinal()); ?>
                            <?php $arrCategoriaPeso = $categoria_peso->getCategoriaPesoToArray($item->getIdCategoriaPeso()); ?>
                            <?php $arrCategoriaIdade = $categoria_idade->getCategoriaIdadeToArray($item->getIdCategoriaIdade()); ?>
                            <?php $arrSexo = $sexo->getSexoToArray($item->getIdSexo()); ?>
                            <tr>
                                <td><?=$arrRegrasLutas['nm_regra_luta']?></td>
                                <td><?=$arrCategoriaIdade['nm_categoria_idade'] . ' - (' .$item->getNrIdadeInicial() . ' ate ' . $item->getNrIdadeFinal() . ')'?></td>
                                <td><?=$arrSexo['nm_sexo']?></td>
                                <td><?=$arrCategoriaPeso['nm_categoria_peso'] . ' - (' . $item->getNrPesoInicial(). ' ate ' . $item->getNrPesoFinal() . ')'?></td>
                                <td align="center"><img alt="<?=$arrGraduacaoInicial['nm_graduacao']?>" height="42" width="42" src="/assets/img/graduacoes/<?=$arrGraduacaoInicial['nm_graduacao']?>.jpeg" /><br /><?=$arrGraduacaoInicial['nm_graduacao']?></td>
                                <td align="center"><img alt="<?=$arrGraduacaoFinal['nm_graduacao']?>" height="42" width="42" src="/assets/img/graduacoes/<?=$arrGraduacaoFinal['nm_graduacao']?>.jpeg" /><br /><?=$arrGraduacaoFinal['nm_graduacao']?></td>

                                <td style="width: 150px;">
                                    <?=\Estrutura\Service\HtmlHelper::botaoAlterar($this->url('navegacao',array('controller'=>$controller,'action'=>'cadastro','id'=>Estrutura\Helpers\Cript::enc($item->getId()))))?>
                                    <?=\Estrutura\Service\HtmlHelper::botaoExcluir($this->url('navegacao',array('controller'=>$controller,'action'=>'excluir','id'=>Estrutura\Helpers\Cript::enc($item->getId()))))?>
                                </td>
                            </tr>
                        <?php }; ?>
                        </tbody>
                    </table>
                    <div class="row">
                        <div class="col-md-12">
                            <a href="<?=$this->url('navegacao', ['controller'=>'principal-principal'])?>" class="btn btn-primary" title="Retorna para a Página Principal">Home</a>
                            <a class="btn btn-default" href="<?=$this->url('navegacao',array('controller'=>$controller,'action'=>'cadastro'))?>">Nova Configuração</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>    
</div>
