<link rel="stylesheet" href="/assets/compact-css/jquery.tablesorter.theme.bootstrap.css,jquery.tablesorter.pager.css">

<?php
/** @var $form \areaconhecimento\Form\areaconhecimento */
/** @var $lista \areaconhecimento\Service\areaconhecimento[] */
?>
<div class="page-head">
    <h2>Lista de Palavras Chaves</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="col-md-12">
            <a class="btn btn-default"
               href="<?= $this->url('navegacao', array('controller' => $controller, 'action' => 'cadastro')) ?>"
               title="Adicionar um nova Palavra Chave">Nova Palavra Chave</a>
        </div>
    </div>
    <br/>
    <div class="row" id="palavrachave-pagination"></div>
</div>

<script>
    $(function () {

        $.ajax({
            type: "post",
            dataType: "text",
            cache: false,
            url: '/palavra_chave-palavrachave/index-pagination',
            async: true,
            data: {},
            beforeSend: function () {

                $('#palavrachave-pagination').html(
                    '<div class="row"><div class="col-md-12 text-center"><p><img src="/assets/img/carregando.gif"><p></div></div>'
                );
            },
            success: function (data) {

                $('#palavrachave-pagination').html(data);
            }
        });

    })
</script>
