<link rel="stylesheet" href="/assets/compact-css/jquery.tablesorter.theme.bootstrap.css,jquery.tablesorter.pager.css">


<?php
/** @var $form \Cidade\Form\Cidade */
/** @var $lista \Cidade\Service\Cidade[] */
?>
<div class="page-head">
    <h2>Lista de Cidades</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="col-md-12">
            <a class="btn btn-default" href="<?=$this->url('navegacao',array('controller'=>$controller,'action'=>'cadastro'))?>" title="Adiciona uma nova cidade">Nova Cidade</a>

        </div>
    </div>
    <br />
    <div class="row" id="cidade-pagination"></div>
</div>

<script>
    $(function () {

        $.ajax({
            type: "post",
            dataType: "text",
            cache: false,
            url: '/cidade-cidade/index-pagination',
            async: true,
            data: {
            },
            beforeSend: function () {

                $('#cidade-pagination').html(
                    '<div class="row"><div class="col-md-12 text-center"><p><img src="/assets/img/carregando.gif"><p></div></div>'
                );
            },
            success: function (data) {

                $('#cidade-pagination').html(data);
            }
        });

    })
</script>
