<?php
  /** @var $form \Cidade\Form\Cidade */
  /** @var $lista \Cidade\Service\Cidade[] */
?>
<div class="page-head">
    <h2>Lista de Cidades Brasileiras</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="col-md-12">
            <a class="btn btn-default" href="<?=$this->url('navegacao',array('controller'=>$controller,'action'=>'cadastro'))?>" title="Adiciona uma nova cidade">Nova Cidade</a>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-12">
            <div class="block-flat">
                <div class="content">

                    <table class="table table-bordered dataTable">
                        <thead>
                            <tr>
                                <th>Estado</th>
                                <th>Cidade</th>

                                <th>Ações</th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php $estadoService = new \Estado\Service\EstadoService(); ?>
                        <?php foreach($lista as $item){ ?>
                            <?php
                            $arrEstado = $estadoService->getEstadoToArray($item->getIdEstado());
                            ?>
                            <tr>
                                <td><?=$arrEstado['nm_estado']?></td>
                                <td><?=$item->getNmCidade()?></td>

                                <td style="width: 150px;">
                                    <?=\Estrutura\Service\HtmlHelper::botaoAlterar($this->url('navegacao',array('controller'=>$controller,'action'=>'cadastro','id'=>Estrutura\Helpers\Cript::enc($item->getId()))))?>
                                    <?=\Estrutura\Service\HtmlHelper::botaoExcluir($this->url('navegacao',array('controller'=>$controller,'action'=>'excluir','id'=>Estrutura\Helpers\Cript::enc($item->getId()))))?>
                                </td>
                            </tr>
                        <?php } ?>
                        </tbody>
                    </table>
                    <div class="row">
                        <div class="col-md-12">
                            <a href="<?=$this->url('navegacao', ['controller'=>'principal-principal'])?>" class="btn btn-primary" title="Retorna para a Página Principal">Home</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>    
</div>
