<div class="page-head">
    <h2>Cadastro</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="block-flat">
            <div class="content">
            <?php
	            $form->setAttribute('action', $this->url('navegacao', array('controller'=>$controller,'action' => 'gravar')));
	            $form->setAttribute('class', 'form-horizontal');
	            $form->setAttribute('data-role', 'form');
	            $form->prepare();
	            echo $this->form()->openTag($form);
	            echo $this->formHidden($form->get('id'));
            ?>
                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('nm_concluinte'))?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                        <?= $this->formRow($form->get('nr_matricula')) ?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                        <?= $this->formRow($form->get('id_curso')) ?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                        <?= $this->formRow($form->get('id_tcc')) ?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-10">
                        <button type="submit" class="btn btn-primary">Salvar</button>
                        <a href="<?=$this->url('navegacao', ['controller'=>$controller])?>" class="btn btn-default">Voltar</a>
                    </div>
                </div>
                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>
