<div class="page-head">
    <h2>Cadastro</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="block-flat">
            <div class="content">
            <?php
	            $form->setAttribute('action', $this->url('navegacao', array('controller'=>$controller,'action' => 'gravar')));
	            $form->setAttribute('class', 'form-horizontal');
	            $form->setAttribute('data-role', 'form');
	            $form->prepare();
	            echo $this->form()->openTag($form);
	            echo $this->formHidden($form->get('id'));
            ?>

                <div class="panel panel-primary">
                    <div class="panel-heading">Dados do Aluno Concluinte</div>
                    <div class="panel-body" style="background-color: #F7F7F7">

                        <div class="container">
                            <div class="row">
                                <div class="form-group">
                                    <div class="col-md-4">
                                        <?=$this->formRow($form->get('nm_concluinte'))?>
                                    </div>
                                    <div class="col-md-4">
                                        <?= $this->formRow($form->get('nr_matricula')) ?>
                                    </div>

                                </div>

                            </div>
                            <div class="row">
                                <div class="form-group">
                                    <div class="col-md-4">
                                        <?= $this->formRow($form->get('id_curso')) ?>
                                    </div>
                                    <div class="col-md-4">
                                        <?= $this->formRow($form->get('id_tcc')) ?>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <div class="col-md-10">
                                            <button type="submit" class="btn btn-primary">Salvar</button>
                                            <a href="<?=$this->url('navegacao', ['controller'=>$controller])?>" class="btn btn-default">Voltar</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                  <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" language="javascript" class="init">
    $(document).ready(function () {
        //Colocar o foco no Concluinte.
        $("#nm_concluinte").focus();

        //Implementar o Conluinte para receber somente numeros na matricula
        $(function() {

            // Somente números
            $( '#nr_matricula' ).on( 'keydown', function(e) {
                var keyCode = e.keyCode || e.which,
                    pattern = /\d/,
                // Permite somente Backspace, Delete e as setas direita e esquerda, números do teclado numérico - 96 a 105 - (além dos números)
                    keys = [ 46, 8, 9, 37, 39, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105 ];

                if( ! pattern.test( String.fromCharCode( keyCode ) ) && $.inArray( keyCode, keys ) === -1 ) {
                    return false;
                }
            });

        });

    });
</script>