<div class="page-head">
    <h2>Alteraçao</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="block-flat">
            <div class="content">
            <?php
            $form->setAttribute('action', $this->url('navegacao', array('controller'=>$controller,'action' => 'gravaralteracaoviaacademia')));
            $form->setAttribute('class', 'form-horizontal');
            $form->setAttribute('data-role', 'form');
            $form->prepare();
            echo $this->form()->openTag($form);

            $academia = new \Academia\Service\AcademiaService();
            $arrAcademia = $academia->getAcademiaToArray($id_academia);

            #Recuperando o Nome de Uma Cidade Pelo ID e Setando no Formulario
            $cidade = new \Cidade\Service\CidadeService();
            $arrCidade = $cidade->getCidadeToArray($id_cidade);
            $form->setData(['id_cidade' => $arrCidade['nm_cidade']]);

            $dt_nascimento = Estrutura\Helpers\Data::converterDataBancoMySQL2Brazil($dt_nascimento);
            ?>
                <div class="form-group">
                    <div class="col-md-4">
                        <input type="hidden" class="form-control" id="id_academia" name="id_academia" value="<?= $id_academia?>" />
                        <input type="hidden" class="form-control" id="id_atleta" name="id_atleta" value="<?= $id_atleta ?>" />
                        <input type="hidden" class="form-control" id="id_usuario" name="id_usuario" value="<?= $this->Auth()->id_usuario?>" />
                        <input type="hidden" class="form-control" id="id_usuario_cadastro" name="id_usuario_cadastro" value="<?= $this->Auth()->id_usuario?>" />
                        <input type="hidden" class="form-control" id="id_cidade" name="id_cidade" value="<?= $arrAcademia['id_cidade'] ?>" />
                        <label for="nm_academia">Academia</label><br />
                        <input type="text" class="form-control" id="nm_academia" name="nm_academia" value="<?= $arrAcademia['nm_academia']?>" readonly />
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                        <label for="nm_atleta">Atleta</label><br />
                        <input type="text" class="form-control" id="nm_atleta" name="nm_atleta" value="<?= $nm_atleta?>" />
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                        <label for="id_sexo">Sexo</label>
                        <select id="id_sexo" class="form-control" data-source="arrId_sexo" data-ng-options="k as v for (k,v) in arrId_sexo" name="id_sexo">
                            <option value="">Selecione...</option>
                            <?php if($id_sexo == 1){ ?>
                                <option value="1" selected>Marculino</option>
                                <option value="2">Feminino</option>
                            <?php } else if( $id_sexo == 2) {?>
                                <option value="1" >Marculino</option>
                                <option value="2" selected>Feminino</option>
                            <?php } else {?>
                                <option value="1" >Marculino</option>
                                <option value="2" >Feminino</option>
                            <?php }?>
                        </select>
                    </div>
                </div>

                <!-- Alysson - Customizado para Adicionar Imagens -->
                <div class="form-group">
                    <div class="col-md-10">
                        <?php
                        ###################################################################
                        #Recuperando Todos os Dados das Graduaçoes
                        $graduacao = new \Graduacao\Service\GraduacaoService();
                        $arrGraduacao = $graduacao->fetchAll()->toArray();
                        $arrGraduacaoTratado = array();
                        foreach($arrGraduacao as $valor){ ?>
                            <input type="radio" name="id_graduacao" id="id_graduacao_<?=$valor['id_graduacao']?>" value="<?=$valor['id_graduacao']?>" <?= $valor['id_graduacao'] == $id_graduacao ? "checked='checked'" : "" ?>  >
                            <img alt="<?=$valor['nm_graduacao']?>" height="42" width="42" src="/assets/img/graduacoes/<?=$valor['nm_graduacao']?>.jpeg" />
                            <?//=$valor['nm_graduacao']?>&nbsp;&nbsp;&nbsp;
                        <?php } ?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4">
                        <label for="nm_atleta">Peso</label><br />
                        <input type="text" class="form-control" id="nr_peso" name="nr_peso" value="<?= $nr_peso?>" />
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                        <label for="dt_nascimento">Data de Nascimento</label><br />
                        <input type="text" class="form-control" id="dt_nascimento" name="dt_nascimento" value="<?= $dt_nascimento?>" />
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                        <label for="tx_endereco">Endereço</label><br />
                        <input type="text" class="form-control" id="tx_endereco" name="tx_endereco" value="<?= $tx_endereco?>" />
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                        <label for="tx_complemento">Complemento</label><br />
                        <input type="text" class="form-control" id="tx_complemento" name="tx_complemento" value="<?= $tx_complemento?>" />
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                        <label for="id_cidade">Cidade</label><br />
                        <input type="text" class="form-control" id="id_cidade" name="id_cidade" value="<?= $arrCidade['nm_cidade']?>" />
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                        <label for="nr_cep">CEP</label><br />
                        <input type="text" class="form-control cep" id="nr_cep" name="nr_cep" value="<?= $nr_cep?>" />
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-10">
                        <button type="submit" class="btn btn-primary">Salvar</button>
                        <a href="<?=$this->url('navegacao', ['controller'=>'academia-academia','action' => 'cadastrocustomizado', 'id'=>Estrutura\Helpers\Cript::enc($id_academia)])?>" class="btn btn-default">Voltar</a>
                    </div>
                </div>
                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" language="javascript" class="init">
    $(document).ready(function() {
        $( "input#id_cidade" ).autocomplete({
            minLength: 4,
            source: "/cidade-cidade/autocompletecidade"
        });

        $( "#dt_nascimento" ).datepicker(
            { dateFormat: 'dd/mm/yy' }
        );

    });
</script>