<div class="page-head">
    <h2>Cadastro</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="block-flat">
            <div class="content">
            <?php
            $form->setAttribute('action', $this->url('navegacao', array('controller'=>$controller,'action' => 'gravarviaacademia')));
            $form->setAttribute('class', 'form-horizontal');
            $form->setAttribute('data-role', 'form');
            $form->prepare();
            echo $this->form()->openTag($form);

            $academia = new \Academia\Service\AcademiaService();
            $arrAcademia = $academia->getAcademiaToArray($id_academia);

            #Recuperando o Nome de Uma Cidade Pelo ID e Setando no Formulario
            $cidade = new \Cidade\Service\CidadeService();
            $arrCidade = $cidade->getCidadeToArray($form->get('id_cidade')->getValue());
            $form->setData(['id_cidade' => $arrCidade['nm_cidade']]);

            $form->get('dt_nascimento')->setValue(Estrutura\Helpers\Data::converterDataBancoMySQL2Brazil($form->get('dt_nascimento')->getValue()));

            $id_graduacao =  $form->get('id_graduacao')->getValue();
            ?>
                <div class="form-group">
                    <div class="col-md-4">
                        <label for="nm_academia">Academia</label><br />
                        <input type="hidden" class="form-control" id="id_academia" name="id_academia" value="<?= $id_academia?>">
                        <input type="hidden" class="form-control" id="id_usuario" name="id_usuario" value="<?= $this->Auth()->id_usuario?>">
                        <input type="hidden" class="form-control" id="id_usuario_cadastro" name="id_usuario_cadastro" value="<?= $this->Auth()->id_usuario?>">
                        <input type="hidden" class="form-control" id="id_cidade" name="id_cidade" value="<?= $arrAcademia['id_cidade'] ?>">
                        <input type="text" class="form-control" id="nm_academia" name="nm_academia" value="<?= $arrAcademia['nm_academia']?>" readonly>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('nm_atleta'))?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('id_sexo'))?>
                    </div>
                </div>

                <!-- Alysson - Customizado para Adicionar Imagens -->
                <div class="form-group">
                    <div class="col-md-10">
                        <?php
                        ###################################################################
                        #Recuperando Todos os Dados das Graduaçoes
                        $graduacao = new \Graduacao\Service\GraduacaoService();
                        $arrGraduacao = $graduacao->fetchAll()->toArray();
                        $arrGraduacaoTratado = array();
                        foreach($arrGraduacao as $valor){ ?>
                            <input type="radio" name="id_graduacao" id="id_graduacao_<?=$valor['id_graduacao']?>" value="<?=$valor['id_graduacao']?>" <?= $valor['id_graduacao'] == $id_graduacao ? "checked='checked'" : "" ?>  >
                            <img alt="<?=$valor['nm_graduacao']?>" height="42" width="42" src="/assets/img/graduacoes/<?=$valor['nm_graduacao']?>.jpeg" />
                            <?//=$valor['nm_graduacao']?>&nbsp;&nbsp;&nbsp;
                        <?php } ?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('nr_peso'))?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('dt_nascimento'))?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('tx_endereco'))?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('tx_complemento'))?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('id_cidade')) ?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                        <?=$this->formRow($form->get('nr_cep'))?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-10">
                        <button type="submit" class="btn btn-primary">Salvar</button>
                        <a href="<?=$this->url('navegacao', ['controller'=>'academia-academia','action' => 'cadastrocustomizado', 'id'=>Estrutura\Helpers\Cript::enc($id_academia)])?>" class="btn btn-default">Voltar</a>
                    </div>
                </div>
                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" language="javascript" class="init">
    $(document).ready(function() {
        $( "#dt_nascimento" ).datepicker(
            { dateFormat: 'dd/mm/yy' }
        );

        $( "input#id_cidade" ).autocomplete({
            minLength: 4,
            source: "/cidade-cidade/autocompletecidade"
        });
    });
</script>