<?php
  /** @var $form \TipoEvento\Form\TipoEvento */
  /** @var $lista \TipoEvento\Service\TipoEvento[] */
?>
<div class="page-head">
    <h2>Lista de Tipos de Eventos</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="col-md-12">
            <a class="btn btn-default" href="<?=$this->url('navegacao',array('controller'=>$controller,'action'=>'cadastro'))?>" title="Inserir um novo tipo de evento">Novo Tipo de Evento</a>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-12">
            <div class="block-flat">
                <div class="content">

                    <table class="table table-bordered dataTable">
                        <thead>
                            <tr>
                                <th>Tipo Evento</th>

                                <th>Ações</th>
                            </tr>
                        </thead>
                        <tbody>

                        <?php foreach($lista as $item){ ?>
                            <tr>
                                <td><?=$item->getNmTipoEvento()?></td>
                                                                
                                <td style="width: 150px;">
                                    <?=\Estrutura\Service\HtmlHelper::botaoAlterar($this->url('navegacao',array('controller'=>$controller,'action'=>'cadastro','id'=>Estrutura\Helpers\Cript::enc($item->getId()))))?>
                                    <?=\Estrutura\Service\HtmlHelper::botaoExcluir($this->url('navegacao',array('controller'=>$controller,'action'=>'excluir','id'=>Estrutura\Helpers\Cript::enc($item->getId()))))?>
                                </td>
                            </tr>
                        <?php }; ?>
                        </tbody>
                    </table>
                    <div class="row">
                        <div class="col-md-12">
                            <a href="<?=$this->url('navegacao', ['controller'=>'principal-principal'])?>" class="btn btn-primary" title="Retorna para a Página Principal">Home</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>    
</div>
