<div class="page-head">
    <h2>Cadastro do Usuário</h2>
</div>
<div class="row row-offcanvas row-offcanvas-right">
    <div class="col-xs-12 col-sm-12">
        <div class="well">

            <?php
            $form->setAttribute('action', $this->url('navegacao', array('controller' => $controller, 'action' => 'gravar')));
            $form->setAttribute('method', 'post');
            $form->setAttribute('class', 'form-horizontal');
            $form->setAttribute('data-toggle', 'validator');
            $form->prepare();
            echo $this->form()->openTag($form);
            ?>

            <div class="panel panel-primary">
                <div class="panel-heading">Dados do Novo Usuário</div>
                <div class="panel-body" style="background-color: #F7F7F7">

                    <div class="container">
                        <div class="row">
                            <div class="form-group">
                                <div class="col-md-3">
                                    <?= $this->formRow($form->get('id_tipo_usuario')); ?>
                                </div>
                            </div>

                        </div>
                        <div class="row">
                            <div class="form-group">
                                <div class="col-md-4">
                                    <?= $this->formRow($form->get('nm_usuario')) ?>
                                </div>
                                <div class="col-md-4">
                                    <?= $this->formRow($form->get('id_sexo')) ?>
                                </div>

                            </div>

                        </div>
                        <div class="row">
                            <div class="form-group">
                                <div class="col-md-4">
                                    <?= $this->formRow($form->get('em_email')); ?>
                                </div>
                                <div class="col-md-4">
                                    <?= $this->formRow($form->get('em_email_confirm')) ?>
                                </div>

                            </div>

                        </div>
                        <div class="row">
                            <div class="form-group">
                                <div class="col-md-4">
                                    <?= $this->formRow($form->get('pw_senha')) ?>
                                </div>
                                <div class="col-md-4">
                                    <?= $this->formRow($form->get('pw_senha_confirm')) ?>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="form-group">
                                <div class="col-md-10">
                                    <button type="submit" class="btn btn-primary">Salvar</button>
                                    <a href="<?= $this->url('navegacao', ['controller' => 'usuario-usuario', 'action' => 'index']) ?>" class="btn btn-default">Voltar</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <?= $this->form()->closeTag(); ?>
        </div>
    </div>
</div>
<script type="text/javascript" src="/assets/compact-js/moment.js,bootstrap-datetimepicker.min.js,validator.min.js,jquery.mask.min.js,jquery.complexify.js,usuario|usuario|cadastro.js"></script>
