<?php
/** @var $lista \Pesquisar\Service\Pesquisar[] */
?>
<div class="page-head">
    <h2>Pesquisa Avançada TCC</h2>
</div>
<div class="row row-offcanvas row-offcanvas-right">

    <div class="col-xs-12 col-sm-12">
        <div class="well">
            <div class="page-head">
                <br/>

                <div class="block-flat">
                    <div class="content">
                        <?php
                        $form->setAttribute('action', '#');
                        $form->setAttribute('class', 'form-horizontal');
                        $form->setAttribute('method', 'post');
                        $form->setAttribute('data-role', 'form');
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        ?>
                        <div class="panel panel-primary">
                            <div class="panel-heading">Insira os dados para pesquisa</div>
                            <div class="panel-body" style="background-color: #F7F7F7">

                                <div class="container">
                                    <div class="row">
                                        <div class="form-group">
                                            <div class="col-md-2">
                                                <?= $this->formRow($form->get('dt_inicio')) ?>
                                            </div>
                                            <div class="col-md-2">
                                                <?= $this->formRow($form->get('dt_final')) ?>
                                            </div>
                                            <div class="col-md-3">
                                                <?= $this->formRow($form->get('id_tipo_tcc')) ?>
                                            </div>
                                            <div class="col-md-4">
                                                <?= $this->formRow($form->get('id_area_conhecimento')) ?>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="form-group">
                                            <div class="col-md-4">
                                                <?=$this->formRow($form->get('id_professor_orientador'))?>
                                            </div>
                                            <div class="col-md-7">
                                                <?= $this->formRow($form->get('tx_titulo_tcc')) ?>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="form-group">
                                            <div class="col-md-4">
                                                <?=$this->formRow($form->get('id_curso'))?>
                                            </div>
                                            <div class="col-md-4">
                                                <?= $this->formRow($form->get('nm_concluinte')) ?>
                                            </div>
                                            <div class="col-md-3">
                                                <?= $this->formRow($form->get('tx_palavra_chave')) ?>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="form-group">
                                            <div class="col-md-12">
                                                <div class="col-md-10">
                                                    <button id="pesquisar" type="submit" class="btn btn-primary">Pesquisar</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <?= $this->form()->closeTag(); ?>
                    </div>
                </div>
            </div>
            <div class="row" id="detalhesfiltros-pagination"></div>
        </div>
    </div>
</div>
<script type="text/javascript" language="javascript" class="init">
    $(document).ready(function () {
        $("#dt_inicio").datepicker(
            {dateFormat: 'dd/mm/yy'}
        );
        $("#dt_final").datepicker(
            {dateFormat: 'dd/mm/yy'}
        );

        function carregarGridPaginadaAjax() {

            $.ajax({
                type: "post",
                dataType: "text",
                cache: false,
                url: '/pesquisar-pesquisar/detalhes-filtros-pagination',
                async: true,
                data: {
                    dt_inicio: $('#dt_inicio').val(),
                    dt_final: $('#dt_final').val(),
                    id_tipo_tcc: $('#id_tipo_tcc').val(),
                    id_area_conhecimento: $('#id_area_conhecimento').val(),
                    id_professor_orientador: $('#id_professor_orientador').val(),
                    tx_titulo_tcc: $('#tx_titulo_tcc').val(),
                    id_curso: $('#id_curso').val(),
                    nm_concluinte: $('#nm_concluinte').val(),
                    tx_palavra_chave: $('#tx_palavra_chave').val()
                },
                beforeSend: function () {
                    $('#detalhesfiltros-pagination').html(
                        '<div class="row"><div class="col-md-12 text-center"><p><img src="/assets/img/carregando.gif"><p></div></div>'
                    );
                },
                success: function (data) {
                    $('#detalhesfiltros-pagination').html(data);
                }
            });
        }

        $('#pesquisar').click(function() {
            carregarGridPaginadaAjax()
            return false;
        });

    });
</script>



