<link rel="stylesheet" type="text/css" href="/assets/compact-css/selectize.bootstrap2.css"/>
<div class="row row-offcanvas row-offcanvas-right">
    <p align="right">
        <button><a href="/pesquisar-pesquisar">Pesquisar TCC</a></button>
    </p>

    <br/>
    <br/>
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-4">

                <div class="panel panel-info">
                    <div class="panel-heading">
                        <h3 class="light panel-title">Login de acesso</h3>
                    </div>
                    <div class="panel-body">
                        <?php
                        $form = $this->form;
                        $form->setAttribute('action', $this->url('authenticate'));
                        $form->setAttribute('method', 'post');
                        $form->setAttribute('class', 'form-horizontal');

                        $form->prepare();
                        echo $this->form()->openTag($form);
                        ?>

                        <div class="form-group">
                            <div class="col-md-12">
                                <?= $this->formRow($form->get('email')) ?>
                                <div class="help-block with-errors"></div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-12">
                                <?= $this->formRow($form->get('senha')) ?>
                                <div class="help-block with-errors"></div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-12">
                                <button type="submit" class="btn btn-primary">Acessar</button>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12 text-center" style="margin: 4px 0px 4px 0px;">
                                <a href="/auth/esqueci-senha" class="pull-right">Não consigo acessar minha conta</a>
                            </div>
                        </div>
                        <?php
                        echo $this->form()->closeTag();
                        ?>
                    </div>
                </div>
            </div>
            <div class="col-sm-1"></div>

            <div class="col-xs-12 col-sm-6">
                <br/>
                <br/>
                <br/>
                <img src="/assets/img/logo/logo-etec.png" max-width=" 200px" height="200px" align="center"/>
            </div>
        </div>
    </div>
</div>