<div class="page-head">
    <h2>Cadastro dos Concluintes</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="block-flat">
            <div class="content">
                <?php
                $form->setAttribute('action', $this->url('navegacao', array('controller' => 'concluinte-concluinte', 'action' => 'gravar')));
                $form->setAttribute('class', 'form-horizontal');
                $form->setAttribute('data-role', 'form');
                $form->setAttribute('method', 'post');
                $form->prepare();
                echo $this->form()->openTag($form);

                $form->get('id')->setValue(Estrutura\Helpers\Cript::enc($dadosTcc->getId()));
                $form->get('id_plano_mudanca')->setValue($dadosTcc->getId());
                echo $this->formHidden($form->get('id'));
                echo $this->formHidden($form->get('id_tcc'));

                ?>
                <div class="bs-callout bs-callout-primary">
                    <ul class="primary">
                        <li><b>Código:</b> <?= $dadoTcc->getId() ?></li>
                        <li><b>Nº Plano de Mudança:</b> <?= $dadoTcc->getNrMudanca() ?></li>
                        <li><b>Plano Trabalho:</b> <?= $dadoTcc->getNmPlanoTrabalho() ?></li>
                        <li><b>Natureza:</b> <?= $ob_natureza->getNmNatureza() ?></li>
                        <li><b>Área Solicitante:</b> <?= $ob_area_solicitante->getNmAreaSolicitante() ?></li>
                        <li><b>Item Afetado:</b> <?= $dadoTcc->getDsItemAfetado() ?></li>
                        <li><b>Status da Mudança:</b> <?= $dadoTcc->getCdStatus() ?></li>
                    </ul>
                </div>
                <br/>
                <!-- Objetivo -->
                <div class="form-group">
                    <div class="col-md-4">
                        <?= $this->formRow($form->get('ds_objetivo')) ?>
                    </div>
                </div>

                <!-- Componentes -->
                <fieldset class="scheduler-border">
                    <legend class="scheduler-border" style="font-size: 200%;">Componentes</legend>
                    <div id="mensagem_componente"></div>
                    <div class="form-group">
                        <div class="col-md-2">
                            <?= $this->formLabel($form->get('id_local')) ?>
                            <?= $this->FormSelect($form->get('id_local')) ?>
                            <div class="help-block with-errors"></div>
                        </div>
                        <div class="col-md-2">
                            <?= $this->formLabel($form->get('id_tipo_componente')) ?>
                            <?= $this->FormSelect($form->get('id_tipo_componente')) ?>
                            <div class="help-block with-errors"></div>
                        </div>
                        <div class="col-md-3">
                            <?= $this->formLabel($form->get('nm_componente')) ?>
                            <?= $this->formInput($form->get('nm_componente')) ?>
                            <div class="help-block with-errors"></div>
                        </div>
                        <div class="col-md-2">
                            <a style="margin-top: 25px;" id="adicionar_componente" class="btn btn-primary" href="#"
                               title="Adicionar Componente">Add</a>
                        </div>

                    </div>
                    <div class="row" id="listar-componentes"></div>
                </fieldset>

                <!-- Planejamento -->
                <fieldset class="scheduler-border">
                    <legend class="scheduler-border" style="font-size: 200%;">Etapas Planejadas</legend>
                    <div id="mensagem_etapa"></div>
                    <div class="form-group">
                        <div class="col-md-4">
                            <?= $this->formRow($form->get('id_usuario')) ?>
                        </div>
                        <div class="col-md-4">
                            <?= $this->formRow($form->get('ds_etapa_planejamento')) ?>
                        </div>

                        <div class="col-md-2">
                            <?= $this->formLabel($form->get('dt_inicio_previsto')) ?>
                            <div class="input-group" id="datetimepicker">
                                                <span class="input-group-addon"><span
                                                        class="glyphicon glyphicon-calendar"></span></span>
                                <?= $this->formInput($form->get('dt_inicio_previsto')) ?>
                            </div>
                            <div class="help-block with-errors"></div>
                        </div>
                        <div class="col-md-2">
                            <?= $this->formLabel($form->get('hr_inicio_previsto')) ?>
                            <div class="input-group">
                                    <span class="input-group-addon"><span
                                            class="glyphicon glyphicon-time"></span></span>
                                <?= $this->formInput($form->get('hr_inicio_previsto')) ?>
                            </div>
                            <div class="help-block with-errors"></div>
                        </div>

                        <div class="col-md-2">
                            <?= $this->formLabel($form->get('dt_fim_previsto')) ?>
                            <div class="input-group" id="datetimepicker">
                                                <span class="input-group-addon"><span
                                                        class="glyphicon glyphicon-calendar"></span></span>
                                <?= $this->formInput($form->get('dt_fim_previsto')) ?>
                            </div>
                            <div class="help-block with-errors"></div>
                        </div>
                        <div class="col-md-2">
                            <?= $this->formLabel($form->get('hr_fim_previsto')) ?>
                            <div class="input-group">
                                    <span class="input-group-addon"><span
                                            class="glyphicon glyphicon-time"></span></span>
                                <?= $this->formInput($form->get('hr_fim_previsto')) ?>
                            </div>
                            <div class="help-block with-errors"></div>
                        </div>
                        <div class="col-md-2">
                            <a style="margin-top: 25px;" id="adicionar_etapa" class="btn btn-primary" href="#"
                               title="Adicionar Etapa de Planejamento">Add</a>
                        </div>
                    </div>
                    <!-- LISTAGEM DAS ETAPAS PLANEJADAS PARA A MUDANÇA -->
                    <div class="row" id="listar-etapas"></div>
                </fieldset>

                <fieldset class="scheduler-border">
                    <legend class="scheduler-border" style="font-size: 200%;">Riscos e Impactos envolvendo a mudança</legend>
                    <div class="col-md-6">
                        <!-- Impactos e Indisponibilidades -->
                        <fieldset class="scheduler-border">
                            <legend class="scheduler-border">Impactos e Indisponibilidades
                            </legend>
                            <div class="form-group">
                                <div class="col-md-10">
                                    <?= $this->formRow($form->get('ds_indisponibilidades')) ?>
                                </div>
                            </div>
                        </fieldset>
                    </div>
                    <div class="col-md-6">
                        <!-- Riscos em não fazer a mudança -->
                        <fieldset class="scheduler-border">
                            <legend class="scheduler-border">Riscos em não fazer a mudança
                            </legend>
                            <div class="form-group">
                                <div class="col-md-10">
                                    <?= $this->formRow($form->get('ds_riscos')) ?>
                                </div>
                            </div>
                        </fieldset>
                    </div>
                </fieldset>

                <!-- Planos de Retorno em caso de falha -->
                <fieldset class="scheduler-border">
                    <legend class="scheduler-border" style="font-size: 200%;">Plano de retorno em caso de falha</legend>
                    <div class="col-md-6">
                        <!-- Backup -->
                        <fieldset class="scheduler-border">
                            <legend class="scheduler-border">Backup</legend>
                            <div class="form-group">
                                <div class="col-md-10">
                                    <?= $this->formRow($form->get('ds_plano_backup')) ?>
                                </div>
                            </div>
                        </fieldset>
                    </div>
                    <!-- Roollback -->
                    <div class="col-md-6">
                        <fieldset class="scheduler-border">
                            <legend class="scheduler-border">Rollback</legend>
                            <div class="form-group">
                                <div class="col-md-10">
                                    <?= $this->formRow($form->get('ds_plano_rollback')) ?>
                                </div>
                            </div>
                        </fieldset>
                    </div>
                </fieldset>
                <div class="form-group">
                    <div class="col-md-10">
                        <button type="submit" class="btn btn-primary">Salvar</button>
                        <a href="<?= $this->url('navegacao', ['controller' => $controller]) ?>" class="btn btn-default">Voltar</a>
                    </div>
                </div>
                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" language="javascript" class="init">
    $(document).ready(function () {
        //Inicia com a área de mensagens oculta
        $('#mensagem_componente').hide();
        $('#mensagem_etapa').hide();

        $("#dt_inicio_previsto").datepicker(
            {dateFormat: 'dd/mm/yy'}
        );
        $("#dt_fim_previsto").datepicker(
            {dateFormat: 'dd/mm/yy'}
        );

        //Função que faz a listagem ser paginada.
        function carregarComponentesAjax() {
            $.ajax({
                type: "post",
                dataType: "text",
                cache: false,
                url: '/plano_mudanca-planomudanca/listar-componentes',
                async: true,
                data: {
                    id_plano_mudanca_detalhe: <?=$id_plano_mudanca_detalhe?> //Parametro passado pela controller
                },
                beforeSend: function () {
                    $('#listar-componentes').html(
                        '<div class="row"><div class="col-md-12 text-center"><p><img src="/assets/img/carregando.gif"><p></div></div>'
                    );
                },
                success: function (data) {
                    $('#listar-componentes').html(data);
                }
            });
        }

        //Função que faz a listagem ser paginada.
        function carregarEtapasPlanejamentoAjax() {
            $.ajax({
                type: "post",
                dataType: "text",
                cache: false,
                url: '/plano_mudanca-planomudanca/listar-etapas-planejamento',
                async: true,
                data: {
                    id_plano_mudanca_detalhe: <?=$id_plano_mudanca_detalhe?> //Parametro passado pela controller
                },
                beforeSend: function () {
                    $('#listar-etapas').html(
                        '<div class="row"><div class="col-md-12 text-center"><p><img src="/assets/img/carregando.gif"><p></div></div>'
                    );
                },
                success: function (data) {
                    $('#listar-etapas').html(data);
                }
            });
        }

        //Faz a chamada de todas as listagens Ajax do formulário
        carregarComponentesAjax();
        carregarEtapasPlanejamentoAjax();

        /*Função Ajax que adiciona os Compopnentes ao Banco de dados*/
        $('#adicionar_componente').click(function () {
            //var dados = $('#componentesform').serialize();
            var dados = $('#planomudancadetalheform').serialize();
            $.ajax({
                type: 'POST',
                dataType: 'json',
                url: '/plano_mudanca-planomudanca/adicionar-componentes',
                async: true,
                data: dados,
                success: function (response) {
                    $('#mensagem_componente').removeClass("bs-callout bs-callout-danger").addClass("bs-callout bs-callout-success");
                    $("#nm_componente").val("");
                    if (response.sucesso == true) {
                        $('#mensagem_componente').show();
                        $('#mensagem_componente').html("<p>Componente relacionado ao plano com sucesso!</p>");
                        carregarComponentesAjax();
                        setTimeout(function () {
                            $('#mensagem_componente').hide(); // "mensagem_componente" é o id do elemento que seja manipular.
                        }, 4500); // O valor é representado em milisegundos.
                    } else {
                        $('#mensagem_componente').show();
                        $('#mensagem_componente').html("<p>Este componente já esta presente no Plano de Trabalho!</p>");
                        $('#mensagem_componente').removeClass("bs-callout bs-callout-success").addClass("bs-callout bs-callout-danger");
                        setTimeout(function () {
                            $('#mensagem_componente').hide(); // "mensagem_componente" é o id do elemento que seja manipular.
                        }, 4500); // O valor é representado em milisegundos.
                    }
                }
            });

        });

        /*Função Ajax que adiciona as janelas de horario ao Banco de dados*/
        $('#adicionar_etapa').click(function () {
            var dados = $('#planomudancadetalheform').serialize();
            $.ajax({
                type: 'POST',
                dataType: 'json',
                url: '/plano_mudanca-planomudanca/adicionar-etapa-planejamento',
                async: true,
                data: dados,
                success: function (response) {
                    $('#mensagem_etapa').removeClass("bs-callout bs-callout-danger").addClass("bs-callout bs-callout-success");
                    $("#ds_etapa_planejamento").val("");
                    if (response.sucesso == true) {
                        $('#mensagem_etapa').show();
                        $('#mensagem_etapa').html("<p>Etapa relacionada ao plano com sucesso!</p>");
                        carregarEtapasPlanejamentoAjax();
                        setTimeout(function () {
                            $('#mensagem_etapa').hide(); // "mensagem_componente" é o id do elemento que seja manipular.
                        }, 4500); // O valor é representado em milisegundos.
                    } else {
                        $('#mensagem_etapa').show();
                        $('#mensagem_etapa').html("<p>Esta Etapa já esta presente no Plano de Trabalho!</p>");
                        $('#mensagem_etapa').removeClass("bs-callout bs-callout-success").addClass("bs-callout bs-callout-danger");
                        setTimeout(function () {
                            $('#mensagem_etapa').hide(); // "mensagem_componente" é o id do elemento que seja manipular.
                        }, 4500); // O valor é representado em milisegundos.
                    }
                }
            });

        });

    });
</script>