<div class="page-head">
    <h2>Dados do TCC cadastrado</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="block-flat">
            <div class="content">
                <?php
                $form->setAttribute('action', $this->url('navegacao', array('controller' => 'concluinte-concluinte', 'action' => 'gravar')));
                $form->setAttribute('class', 'form-horizontal');
                $form->setAttribute('data-role', 'form');
                $form->setAttribute('method', 'post');
                $form->prepare();
                echo $this->form()->openTag($form);
                $form->get('id')->setValue(Estrutura\Helpers\Cript::enc($dadosTcc->getId()));
                $form->get('id_tcc')->setValue($dadosTcc->getId());
                echo $this->formHidden($form->get('id'));
                echo $this->formHidden($form->get('id_tcc'));
                //----------------------
                //Objetos criados para Recuperar o Nomes e Data pelo ID
                ##
                $areaBancaExaminadoraService = new \BancaExaminadora\Service\BancaExaminadoraService();
                $obj_banca_examinadora = $areaBancaExaminadoraService->buscar($dadosTcc->getIdBancaExaminadora());
                ##
                $areaTipoTccService = new \TipoTcc\Service\TipoTccService();
                $obj_tipo_tcc = $areaTipoTccService->buscar($dadosTcc->getIdTipoTcc());
                ##
                $areaAreaConhecimentoService = new \Areaconhecimento\Service\AreaConhecimentoService();
                $obj_area_conhecimento = $areaAreaConhecimentoService->buscar($dadosTcc->getIdAreaConhecimento());
                ##
                $areaProfessorOrientadorService = new \Professor\Service\ProfessorService();
                $obj_Prof_orientador = $areaProfessorOrientadorService->buscar($dadosTcc->getIdProfessorOrientador());
                //----------------------
                #xd($dadosTcc);
                ?>
                <div class="bs-callout bs-callout-primary">
                    <div class="row">
                        <div class="col-md-12">
                            <h4><b>Registro nº:</b> <?= $dadosTcc->getId() ?></h4>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            <b>Data da
                                Banca:</b> <?= Estrutura\Helpers\Data::converterDataBancoMySQL2Brazil($obj_banca_examinadora->getDtBanca()) ?>
                        </div>
                        <div class="col-md-5">
                            <b>Título:</b> <?= $dadosTcc->getTxTituloTcc() ?>
                        </div>
                        <div class="col-md-4">
                            <b>Area de Conhecimento:</b> <?= $obj_area_conhecimento->getNmAreaConhecimento() ?>

                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            <b>Tipo:</b> <?= $obj_tipo_tcc->getNmTipoTcc() ?>
                        </div>
                        <div class="col-md-5">
                            <b>Professor Orientador:</b> <?= $obj_Prof_orientador->getNmProfessor() ?>
                        </div>
                        <div class="col-md-4">
                            <b>Nota do Trabalho:</b> <?= $dadosTcc->getNrNotaFinal() ?>
                        </div>
                    </div>
                </div>

                <!-- Concluintes -->
                <fieldset class="scheduler-border">
                    <legend class="scheduler-border" style="font-size: 200%;">Adicionar Alunos ao TCC</legend>
                    <div id="mensagem_concluinte"></div>
                    <div class="form-group">
                        <div class="col-md-4">
                            <?= $this->formRow($form->get('nm_concluinte')) ?>
                            <div class="help-block with-errors"></div>
                        </div>
                        <div class="col-md-2">
                            <?= $this->formRow($form->get('nr_matricula')) ?>
                            <div class="help-block with-errors"></div>
                        </div>
                        <div class="col-md-4">
                            <?= $this->formRow($form->get('id_curso')) ?>
                            <div class="help-block with-errors"></div>
                        </div>
                        <div class="col-md-2">
                            <a style="margin-top: 25px;" id="adicionar_concluinte" class="btn btn-primary" href="#">Adicionar</a>
                        </div>
                    </div>
                    <div class="row" id="listar-concluintes"></div>
                </fieldset>

                <!-- Palavra Chave -->
                <fieldset class="scheduler-border">
                    <legend class="scheduler-border" style="font-size: 200%;">Adicionar Palavra Chave</legend>
                    <div id="mensagem_palavra_chave"></div>
                    <div class="form-group">
                        <div class="col-md-4">
                            <?= $this->formRow($form->get('id_palavra_chave')) ?>
                            <div class="help-block with-errors"></div>
                        </div>

                        <div class="col-md-2">
                            <a style="margin-top: 25px;" id="adicionar_palavra_chave" class="btn btn-primary" href="#">Adicionar</a>
                        </div>
                    </div>
                    <div class="row" id="listar-palavrachavetcc"></div>
                </fieldset>


                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript"
        src="/assets/compact-js/moment.js,bootstrap-datetimepicker.min.js,validator.min.js,jquery.mask.min.js,jquery.complexify.js,usuario|usuario|cadastro.js"></script>
<script type="text/javascript" language="javascript" class="init">
    $(document).ready(function () {
        $('#mensagem_palavra_chave').hide();
        $('#mensagem_concluinte').hide();
        //Função que faz a listagem ser paginada.
        function carregarPalavraChaveTccAjax() {
            $.ajax({
                type: "post",
                dataType: "text",
                cache: false,
                url: '/tcc-tcc/listar-palavrachavetcc',
                async: true,
                data: {id_tcc: <?=$dadosTcc->getId()?>},
                beforeSend: function () {
                    $('#listar-palavrachavetcc').html(
                        '<div class="row"><div class="col-md-12 text-center"><p><img src="/assets/img/carregando.gif"><p></div></div>'
                    );
                },
                success: function (data) {
                    $('#listar-palavrachavetcc').html(data);
                }
            });
        }

        //Função que faz a listagem ser paginada.
        function carregarConcluinteAjax() {
            $.ajax({
                type: "post",
                dataType: "text",
                cache: false,
                url: '/tcc-tcc/listar-concluintes',
                async: true,
                data: {id_tcc: <?=$dadosTcc->getId()?>},
                beforeSend: function () {
                    $('#listar-concluintes').html(
                        '<div class="row"><div class="col-md-12 text-center"><p><img src="/assets/img/carregando.gif"><p></div></div>'
                    );
                },
                success: function (data) {
                    $('#listar-concluintes').html(data);
                }
            });
        }

        carregarPalavraChaveTccAjax(); //Chama a Paginação da listagem
        carregarConcluinteAjax(); //Chama a Paginação da listagem

        /*Função Ajax que adiciona os encontros ao Banco de dados*/
        $('#adicionar_palavra_chave').click(function () {
            var dados = $('#tccdetalheform').serialize();
            $.ajax({
                type: 'POST',
                dataType: 'json',
                url: '/tcc-tcc/adicionar-palavrachavetcc',
                async: true,
                data: dados,
                success: function (response) {
                    $('#mensagem_palavra_chave').removeClass("bs-callout bs-callout-danger").addClass("bs-callout bs-callout-success");
                    $("#id_palavra_chave").val("");
                    if (response.sucesso == true) {
                        $('#mensagem_palavra_chave').show();
                        $('#mensagem_palavra_chave').html("<p>Palavra chave adicionada com sucesso!</p>");
                        carregarPalavraChaveTccAjax();
                        setTimeout(function () {
                            $('#mensagem_palavra_chave').fadeOut('fast'); // "mensagem_professor" fechará após 3 minutos.
                        }, 3000); // O valor é representado em milisegundos.
                    } else {
                        $('#mensagem_palavra_chave').show();
                        $('#mensagem_palavra_chave').html("<p>A Palavra chave já foi adicionada!</p>");
                        $('#mensagem_palavra_chave').removeClass("bs-callout bs-callout-success").addClass("bs-callout bs-callout-danger");
                        setTimeout(function () {
                            $('#mensagem_palavra_chave').fadeOut('fast'); // "mensagem_professor" fechará após 3 minutos.
                        }, 3000); // O valor é representado em milisegundos.
                    }
                }
            });
        });

        /*Função Ajax que adiciona os encontros ao Banco de dados*/
        $('#adicionar_concluinte').click(function () {
            var dados = $('#tccdetalheform').serialize();
            $.ajax({
                type: 'POST',
                dataType: 'json',
                url: '/tcc-tcc/adicionar-concluintes',
                async: true,
                data: dados,
                success: function (response) {
                    $('#mensagem_concluinte').removeClass("bs-callout bs-callout-danger").addClass("bs-callout bs-callout-success");
                    $("#nm_concluinte").val("");
                    $("#nr_matricula").val("");
                    if (response.sucesso == true) {
                        $('#mensagem_concluinte').show();
                        $('#mensagem_concluinte').html("<p>Aluno [" + response.nm_concluinte + "] foi adicionado com sucesso!</p>");
                        carregarConcluinteAjax();
                        setTimeout(function () {
                            $('#mensagem_concluinte').fadeOut('fast'); // "mensagem_professor" fechará após 3 minutos.
                        }, 3000); // O valor é representado em milisegundos.
                    } else {
                        $('#mensagem_concluinte').show();
                        $('#mensagem_concluinte').html("<p>Este Aluno já foi adicionado!</p>");
                        $('#mensagem_concluinte').removeClass("bs-callout bs-callout-success").addClass("bs-callout bs-callout-danger");
                        setTimeout(function () {
                            $('#mensagem_concluinte').fadeOut('fast'); // "mensagem_professor" fechará após 3 minutos.
                        }, 3000); // O valor é representado em milisegundos.
                    }
                }
            });
        });

        //Colocar o foco no Concluinte.
        $("#nm_concluinte").focus();

    });
</script>