    <div class="page-head">
    <h2>Dados do TCC cadastrado</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="block-flat">
            <div class="content">
                <?php
                $form->setAttribute('action', $this->url('navegacao', array('controller' => 'concluinte-concluinte', 'action' => 'gravar')));
                $form->setAttribute('class', 'form-horizontal');
                $form->setAttribute('data-role', 'form');
                $form->setAttribute('method', 'post');
                $form->prepare();

                echo $this->form()->openTag($form);

                $form->get('id')->setValue(Estrutura\Helpers\Cript::enc($dadosTcc->getId()));
                $form->get('id_tcc')->setValue($dadosTcc->getId());

                echo $this->formHidden($form->get('id'));
                echo $this->formHidden($form->get('id_tcc'));

                //----------------------
                //Objetos criados para Recuperar o Nomes e Data pelo ID
                ##
                $areaBancaExaminadoraService = new \BancaExaminadora\Service\BancaExaminadoraService();
                $ob_banca_examinadora = $areaBancaExaminadoraService->buscar($dadosTcc->getIdBancaExaminadora());
                ##
                $areaTipoTccService = new \TipoTcc\Service\TipoTccService();
                $ob_tipo_tcc = $areaTipoTccService->buscar($dadosTcc->getIdTipoTcc());
                ##
                $areaAreaConhecimentoService = new \Areaconhecimento\Service\AreaConhecimentoService();
                $ob_area_conhecimento = $areaAreaConhecimentoService->buscar($dadosTcc->getIdAreaConhecimento());
                ##
                $areaProfessorOrientadorService = new \Professor\Service\ProfessorService();
                $ob_Prof_orientador = $areaProfessorOrientadorService->buscar($dadosTcc->getIdProfessorOrientador());
                //----------------------

                #xd($dadosTcc);
                ?>
                        <div class="bs-callout bs-callout-primary">
                            <ul class="primary">
                                <li><b>Registro nº:</b> <?= $dadosTcc->getId() ?></li>
                                <li><b>Data da Banca:</b> <?= Estrutura\Helpers\Data::converterDataBancoMySQL2Brazil($ob_banca_examinadora->getDtBanca()) ?></li>
                                <li><b>Titulo:</b> <?= $dadosTcc->getTxTituloTcc() ?></li>
                                <li><b>Tipo:</b> <?= $ob_tipo_tcc->getNmTipoTcc() ?></li>
                                <li><b>Area de Conhecimento:</b> <?= $ob_area_conhecimento->getNmAreaConhecimento() ?></li>
                                <li><b>Professor Orientador:</b> <?= $ob_Prof_orientador->getNmProfessor() ?></li>
                                <li><b>Nota do Trabalho:</b> <?= $dadosTcc->getNrNotaFinal() ?></li>
                            </ul>
                        </div>
                <?php
                $form->setAttribute('action', '#');
                $form->setAttribute('class', 'form-horizontal');
                $form->setAttribute('method', 'post');

                $form->prepare();
                echo $this->form()->openTag($form);
                $form->get('id')->setValue($dadosTcc->getId());
                $form->get('nm_concluinte')->setValue($form->get('nm_concluinte')->getValue());
                echo $this->formHidden($form->get('id'));

                ?>
                <legend>Cadastrar aluno no TCC</legend>

                <div class="container">
                    <div class="row">

                        <div class="form-group">
                            <div class="col-md-3">
                                <div class="input-group">
                                    <?= $this->formRow($form->get('id_curso')) ?>
                                    <div class="help-block with-errors"></div>

                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="input-group">
                                    <?= $this->formRow($form->get('nm_concluinte')) ?>
                                    <div class="help-block with-errors"></div>

                                </div>
                            </div>
                            <div class="col-md-2">
                                <div class="input-group">
                                    <?= $this->formRow($form->get('nr_matricula')) ?>
                                    <div class="help-block with-errors"></div>

                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="input-group">
                                    <a style="margin-top: 25px;" id="adicionar" class="btn btn-primary" href="#">Adicionar Aluno</a>
                                    <a style="margin-top: 25px;" id="Salvar" class="btn btn-default" href="#">Salvar dados</a>
                                </div>
                                <div class="help-block with-errors"></div>
                            </div>
                        </div>
                    </div>

                </div>
               
                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
    <div class="row" id="detalhe-pagination"></div>
</div>
<script type="text/javascript"
        src="/assets/compact-js/moment.js,bootstrap-datetimepicker.min.js,validator.min.js,jquery.mask.min.js,jquery.complexify.js,usuario|usuario|cadastro.js"></script>
<script type="text/javascript" language="javascript" class="init">
    $(document).ready(function () {

        //Função que faz a listagem ser paginada.
        function carregarGridPaginadaAjax() {
            $.ajax({
                type: "post",
                dataType: "text",
                cache: false,
                url: '/tcc-tcc/detalhe-pagination',
                async: true,
                data: {id_tcc: <?=$dadosTcc->getId()?>},
                beforeSend: function () {
                    $('#detalhe-pagination').html(
                        '<div class="row"><div class="col-md-12 text-center"><p><img src="/assets/img/carregando.gif"><p></div></div>'
                    );
                },
                success: function (data) {
                    $('#detalhe-pagination').html(data);
                }
            });
        }

        carregarGridPaginadaAjax(); //Chama a Paginação da listagem

        /*Função Ajax que adiciona os encontros ao Banco de dados*/
        $('#adicionar').click(function () {
            var dados = $('#detalhetccform').serialize();
            $.ajax({
                type: 'POST',
                dataType: 'json',
                url: '/tcc-tcc/adicionardetalhetcc',
                async: true,
                data: dados,
                success: function (response) {
                    $("#nm_concluinte").val("");
                    if (response.sucesso == true) {
                        carregarGridPaginadaAjax();
                    }
                }
            });

            return false;
        });

    });
</script>
