<div class="page-head">
    <h2>Cadastro</h2>
</div>
<div class="row row-offcanvas row-offcanvas-right">

<div class="col-xs-12 col-sm-12">
    <div class="well">
        <div class="page-head">
            <?php
            $form->setAttribute('action', $this->url('navegacao', array('controller' => $controller, 'action' => 'gravar')));
            $form->setAttribute('class', 'form-horizontal');
            $form->setAttribute('method', 'post');
            $form->setAttribute('data-role', 'form');
            $form->prepare();
            echo $this->form()->openTag($form);
            $form->get('id')->setValue(Estrutura\Helpers\Cript::enc($form->get('id')->getValue()));
            $form->get('id_usuario_cadastro')->setValue($this->Auth()->id_usuario);
            $form->get('id_usuario_alteracao')->setValue($this->Auth()->id_usuario);

            echo $this->formHidden($form->get('id'));
            echo $this->formHidden($form->get('id_usuario_cadastro'));
            echo $this->formHidden($form->get('id_usuario_alteracao'));

            ?>

            <div class="panel panel-primary">
                <div class="panel-heading">Dados dos TCC</div>
                    <div class="panel-body" style="background-color: #F7F7F7">

                    <div class="container">
                        <div class="row">
                            <div class="form-group" id="datetimepicker">
                                <div class="col-md-4">
                                    <?= $this->formRow($form->get('id_banca_examinadora')); ?>
                                </div>
                                <div class="col-md-4">
                                    <?= $this->formRow($form->get('tx_titulo_tcc')) ?>
                                </div>
                                <div class="col-md-3">
                                    <?= $this->formRow($form->get('id_tipo_tcc')) ?>
                                </div>
                            </div>

                        </div>
                        <div class="row">
                            <div class="form-group">
                                <div class="col-md-4">
                                    <?= $this->formRow($form->get('id_area_conhecimento')); ?>
                                </div>
                                <div class="col-md-4">
                                    <?= $this->formRow($form->get('id_professor_orientador')) ?>
                                </div>
                                <div class="col-md-3">
                                    <?= $this->formRow($form->get('nr_nota_final')) ?>
                                </div>
                            </div>

                        </div>
                        <div class="row">
                            <div class="form-group">
                                <div class="col-md-11">
                                    <?= $this->formRow($form->get('tx_resumo')) ?>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group">
                                <div class="col-md-4">
                                    <?= $this->formRow($form->get('ar_arquivo')) ?>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group">
                                <div class="col-md-11">
                                    <button type="submit" class="btn btn-primary">Avançar</button>
                                    <a href="<?= $this->url('navegacao', ['controller' => $controller]) ?>"
                                       class="btn btn-default">Voltar</a></div>
                            </div>
                        </div>
                    </div>
                    </div>

                </div>
            </div>
        </div>
            <?= $this->form()->closeTag(); ?>
    </div>
</div>
</div>
<script type="text/javascript"src="/assets/compact-js/moment.js,bootstrap-datetimepicker.min.js,validator.min.js,jquery.mask.min.js,jquery.complexify.js,usuario|usuario|cadastro.js"></script>

<script type="text/javascript" language="javascript" class="init">
    $(document).ready(function () {
        //Colocar o foco na data da banca.
        $("#id_banca_examinadora").focus();

    });

</script>