

<ul class="primary">
    <li><b>Registro nº:</b> <?= $dadosTcc->getId() ?></li>
    <li><b>Data da
            Banca:</b> <?= Estrutura\Helpers\Data::converterDataBancoMySQL2Brazil($ob_banca_examinadora->getDtBanca()) ?>
    </li>
    <li><b>Titulo:</b> <?= $dadosTcc->getTxTituloTcc() ?></li>
    <li><b>Tipo:</b> <?= $ob_tipo_tcc->getNmTipoTcc() ?></li>
    <li><b>Area de Conhecimento:</b> <?= $ob_area_conhecimento->getNmAreaConhecimento() ?></li>
    <li><b>Professor Orientador:</b> <?= $ob_Prof_orientador->getNmProfessor() ?></li>
    <li><b>Nota do Trabalho:</b> <?= $dadosTcc->getNrNotaFinal() ?></li>
</ul>