<script src="/assets/compact-js/mc-network|cursos|index.js"></script>
<div class="row row-offcanvas row-offcanvas-right">

    <div class="col-xs-12 col-sm-9">

        <div class="panel-group" id="accordion">
            <div class="panel panel-default">
                <div class="panel-heading" id="Collapsible1" style="cursor: pointer;" title="Cursos online">
                    <h4 class="panel-title">
                        Cursos online
                    </h4>
                </div>
                <div id="collapseOne" class="collapse">
                    <div class="panel-body" id="body-collapse-one"></div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading" id="Collapsible2" style="cursor: pointer;" title="Rede">
                    <h4 class="panel-title">
                        Rede
                    </h4>
                </div>
                <div id="collapseTwo" class="collapse">
                    <div class="panel-body" id="body-collapse-Two"></div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading" id="Collapsible3" style="cursor: pointer;" title="Rede Up-line">
                    <h4 class="panel-title">
                        Rede Up-line
                    </h4>
                </div>
                <div id="collapseThree" class="collapse">
                    <div class="panel-body" id="body-collapse-Three"></div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading" id="Collapsible4" style="cursor: pointer;" title="Rede Uni-level">
                    <h4 class="panel-title">
                        Rede Uni-level
                    </h4>
                </div>
                <div id="collapseFour" class="collapse">
                    <div class="panel-body" id="body-collapse-for"></div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading" id="Collapsible5" style="cursor: pointer;" title="Dados Pessoais">
                    <h4 class="panel-title">
                        Dados Pessoais
                    </h4>
                </div>
                <div id="collapseFive" class="collapse">
                    <div class="panel-body" id="body-collapse-five"></div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading" id="Collapsible6" style="cursor: pointer;" title="Extrato">
                    <h4 class="panel-title">
                        Extrato
                    </h4>
                </div>
                <div id="collapseSix" class="collapse">
                    <div class="panel-body" id="body-collapse-six"></div>
                </div>
            </div>
        </div>

    </div>
    <?= $this->partial('partials/menu-left'); ?>
</div>